// AUTO-PORTED from my_flutter_app/lib/data/country_catalog.dart — the complete
// ISO-3166 country list. Keep in sync with the mobile app. This is the canonical
// source for any country picker on the web. Do NOT hardcode a partial country
// list anywhere; import COUNTRY_CATALOG (or COUNTRY_NAMES) instead.
//
// Note: barrel *destination* countries are a deliberately curated subset and
// live separately (operations-panels.tsx `countries`). This catalog is for
// address/location pickers that must offer every country.

export type CountryEntry = { id: string; name: string; code: string };

export const COUNTRY_CATALOG: readonly CountryEntry[] = [
  { id: "afghanistan", name: "Afghanistan", code: "AF" },
  { id: "albania", name: "Albania", code: "AL" },
  { id: "algeria", name: "Algeria", code: "DZ" },
  { id: "american-samoa", name: "American Samoa", code: "AS" },
  { id: "andorra", name: "Andorra", code: "AD" },
  { id: "angola", name: "Angola", code: "AO" },
  { id: "anguilla", name: "Anguilla", code: "AI" },
  { id: "antarctica", name: "Antarctica", code: "AQ" },
  { id: "antigua-and-barbuda", name: "Antigua and Barbuda", code: "AG" },
  { id: "argentina", name: "Argentina", code: "AR" },
  { id: "armenia", name: "Armenia", code: "AM" },
  { id: "aruba", name: "Aruba", code: "AW" },
  { id: "australia", name: "Australia", code: "AU" },
  { id: "austria", name: "Austria", code: "AT" },
  { id: "azerbaijan", name: "Azerbaijan", code: "AZ" },
  { id: "bahamas", name: "Bahamas", code: "BS" },
  { id: "bahrain", name: "Bahrain", code: "BH" },
  { id: "bangladesh", name: "Bangladesh", code: "BD" },
  { id: "barbados", name: "Barbados", code: "BB" },
  { id: "belarus", name: "Belarus", code: "BY" },
  { id: "belgium", name: "Belgium", code: "BE" },
  { id: "belize", name: "Belize", code: "BZ" },
  { id: "benin", name: "Benin", code: "BJ" },
  { id: "bermuda", name: "Bermuda", code: "BM" },
  { id: "bhutan", name: "Bhutan", code: "BT" },
  { id: "bolivia", name: "Bolivia", code: "BO" },
  { id: "bonaire-sint-eustatius-and-saba", name: "Bonaire, Sint Eustatius and Saba", code: "BQ" },
  { id: "bosnia-and-herzegovina", name: "Bosnia and Herzegovina", code: "BA" },
  { id: "botswana", name: "Botswana", code: "BW" },
  { id: "bouvet-island", name: "Bouvet Island", code: "BV" },
  { id: "brazil", name: "Brazil", code: "BR" },
  { id: "british-indian-ocean-territory", name: "British Indian Ocean Territory", code: "IO" },
  { id: "brunei-darussalam", name: "Brunei Darussalam", code: "BN" },
  { id: "bulgaria", name: "Bulgaria", code: "BG" },
  { id: "burkina-faso", name: "Burkina Faso", code: "BF" },
  { id: "burundi", name: "Burundi", code: "BI" },
  { id: "cabo-verde", name: "Cabo Verde", code: "CV" },
  { id: "cambodia", name: "Cambodia", code: "KH" },
  { id: "cameroon", name: "Cameroon", code: "CM" },
  { id: "canada", name: "Canada", code: "CA" },
  { id: "cayman-islands", name: "Cayman Islands", code: "KY" },
  { id: "central-african-republic", name: "Central African Republic", code: "CF" },
  { id: "chad", name: "Chad", code: "TD" },
  { id: "chile", name: "Chile", code: "CL" },
  { id: "china", name: "China", code: "CN" },
  { id: "christmas-island", name: "Christmas Island", code: "CX" },
  { id: "cocos-keeling-islands", name: "Cocos (Keeling) Islands", code: "CC" },
  { id: "colombia", name: "Colombia", code: "CO" },
  { id: "comoros", name: "Comoros", code: "KM" },
  { id: "congo", name: "Congo", code: "CG" },
  { id: "congo-the-democratic-republic-of-the", name: "Congo, The Democratic Republic of the", code: "CD" },
  { id: "cook-islands", name: "Cook Islands", code: "CK" },
  { id: "costa-rica", name: "Costa Rica", code: "CR" },
  { id: "croatia", name: "Croatia", code: "HR" },
  { id: "cuba", name: "Cuba", code: "CU" },
  { id: "cura-ao", name: "Curaçao", code: "CW" },
  { id: "cyprus", name: "Cyprus", code: "CY" },
  { id: "czechia", name: "Czechia", code: "CZ" },
  { id: "c-te-d-ivoire", name: "Côte d'Ivoire", code: "CI" },
  { id: "denmark", name: "Denmark", code: "DK" },
  { id: "djibouti", name: "Djibouti", code: "DJ" },
  { id: "dominica", name: "Dominica", code: "DM" },
  { id: "dominican-republic", name: "Dominican Republic", code: "DO" },
  { id: "ecuador", name: "Ecuador", code: "EC" },
  { id: "egypt", name: "Egypt", code: "EG" },
  { id: "el-salvador", name: "El Salvador", code: "SV" },
  { id: "equatorial-guinea", name: "Equatorial Guinea", code: "GQ" },
  { id: "eritrea", name: "Eritrea", code: "ER" },
  { id: "estonia", name: "Estonia", code: "EE" },
  { id: "eswatini", name: "Eswatini", code: "SZ" },
  { id: "ethiopia", name: "Ethiopia", code: "ET" },
  { id: "falkland-islands-malvinas", name: "Falkland Islands (Malvinas)", code: "FK" },
  { id: "faroe-islands", name: "Faroe Islands", code: "FO" },
  { id: "fiji", name: "Fiji", code: "FJ" },
  { id: "finland", name: "Finland", code: "FI" },
  { id: "france", name: "France", code: "FR" },
  { id: "french-guiana", name: "French Guiana", code: "GF" },
  { id: "french-polynesia", name: "French Polynesia", code: "PF" },
  { id: "french-southern-territories", name: "French Southern Territories", code: "TF" },
  { id: "gabon", name: "Gabon", code: "GA" },
  { id: "gambia", name: "Gambia", code: "GM" },
  { id: "georgia", name: "Georgia", code: "GE" },
  { id: "germany", name: "Germany", code: "DE" },
  { id: "ghana", name: "Ghana", code: "GH" },
  { id: "gibraltar", name: "Gibraltar", code: "GI" },
  { id: "greece", name: "Greece", code: "GR" },
  { id: "greenland", name: "Greenland", code: "GL" },
  { id: "grenada", name: "Grenada", code: "GD" },
  { id: "guadeloupe", name: "Guadeloupe", code: "GP" },
  { id: "guam", name: "Guam", code: "GU" },
  { id: "guatemala", name: "Guatemala", code: "GT" },
  { id: "guernsey", name: "Guernsey", code: "GG" },
  { id: "guinea", name: "Guinea", code: "GN" },
  { id: "guinea-bissau", name: "Guinea-Bissau", code: "GW" },
  { id: "guyana", name: "Guyana", code: "GY" },
  { id: "haiti", name: "Haiti", code: "HT" },
  { id: "heard-island-and-mcdonald-islands", name: "Heard Island and McDonald Islands", code: "HM" },
  { id: "holy-see-vatican-city-state", name: "Holy See (Vatican City State)", code: "VA" },
  { id: "honduras", name: "Honduras", code: "HN" },
  { id: "hong-kong", name: "Hong Kong", code: "HK" },
  { id: "hungary", name: "Hungary", code: "HU" },
  { id: "iceland", name: "Iceland", code: "IS" },
  { id: "india", name: "India", code: "IN" },
  { id: "indonesia", name: "Indonesia", code: "ID" },
  { id: "iran", name: "Iran", code: "IR" },
  { id: "iraq", name: "Iraq", code: "IQ" },
  { id: "ireland", name: "Ireland", code: "IE" },
  { id: "isle-of-man", name: "Isle of Man", code: "IM" },
  { id: "israel", name: "Israel", code: "IL" },
  { id: "italy", name: "Italy", code: "IT" },
  { id: "jamaica", name: "Jamaica", code: "JM" },
  { id: "japan", name: "Japan", code: "JP" },
  { id: "jersey", name: "Jersey", code: "JE" },
  { id: "jordan", name: "Jordan", code: "JO" },
  { id: "kazakhstan", name: "Kazakhstan", code: "KZ" },
  { id: "kenya", name: "Kenya", code: "KE" },
  { id: "kiribati", name: "Kiribati", code: "KI" },
  { id: "north-korea", name: "North Korea", code: "KP" },
  { id: "south-korea", name: "South Korea", code: "KR" },
  { id: "kuwait", name: "Kuwait", code: "KW" },
  { id: "kyrgyzstan", name: "Kyrgyzstan", code: "KG" },
  { id: "laos", name: "Laos", code: "LA" },
  { id: "latvia", name: "Latvia", code: "LV" },
  { id: "lebanon", name: "Lebanon", code: "LB" },
  { id: "lesotho", name: "Lesotho", code: "LS" },
  { id: "liberia", name: "Liberia", code: "LR" },
  { id: "libya", name: "Libya", code: "LY" },
  { id: "liechtenstein", name: "Liechtenstein", code: "LI" },
  { id: "lithuania", name: "Lithuania", code: "LT" },
  { id: "luxembourg", name: "Luxembourg", code: "LU" },
  { id: "macao", name: "Macao", code: "MO" },
  { id: "madagascar", name: "Madagascar", code: "MG" },
  { id: "malawi", name: "Malawi", code: "MW" },
  { id: "malaysia", name: "Malaysia", code: "MY" },
  { id: "maldives", name: "Maldives", code: "MV" },
  { id: "mali", name: "Mali", code: "ML" },
  { id: "malta", name: "Malta", code: "MT" },
  { id: "marshall-islands", name: "Marshall Islands", code: "MH" },
  { id: "martinique", name: "Martinique", code: "MQ" },
  { id: "mauritania", name: "Mauritania", code: "MR" },
  { id: "mauritius", name: "Mauritius", code: "MU" },
  { id: "mayotte", name: "Mayotte", code: "YT" },
  { id: "mexico", name: "Mexico", code: "MX" },
  { id: "micronesia-federated-states-of", name: "Micronesia, Federated States of", code: "FM" },
  { id: "moldova", name: "Moldova", code: "MD" },
  { id: "monaco", name: "Monaco", code: "MC" },
  { id: "mongolia", name: "Mongolia", code: "MN" },
  { id: "montenegro", name: "Montenegro", code: "ME" },
  { id: "montserrat", name: "Montserrat", code: "MS" },
  { id: "morocco", name: "Morocco", code: "MA" },
  { id: "mozambique", name: "Mozambique", code: "MZ" },
  { id: "myanmar", name: "Myanmar", code: "MM" },
  { id: "namibia", name: "Namibia", code: "NA" },
  { id: "nauru", name: "Nauru", code: "NR" },
  { id: "nepal", name: "Nepal", code: "NP" },
  { id: "netherlands", name: "Netherlands", code: "NL" },
  { id: "new-caledonia", name: "New Caledonia", code: "NC" },
  { id: "new-zealand", name: "New Zealand", code: "NZ" },
  { id: "nicaragua", name: "Nicaragua", code: "NI" },
  { id: "niger", name: "Niger", code: "NE" },
  { id: "nigeria", name: "Nigeria", code: "NG" },
  { id: "niue", name: "Niue", code: "NU" },
  { id: "norfolk-island", name: "Norfolk Island", code: "NF" },
  { id: "north-macedonia", name: "North Macedonia", code: "MK" },
  { id: "northern-mariana-islands", name: "Northern Mariana Islands", code: "MP" },
  { id: "norway", name: "Norway", code: "NO" },
  { id: "oman", name: "Oman", code: "OM" },
  { id: "pakistan", name: "Pakistan", code: "PK" },
  { id: "palau", name: "Palau", code: "PW" },
  { id: "palestine-state-of", name: "Palestine, State of", code: "PS" },
  { id: "panama", name: "Panama", code: "PA" },
  { id: "papua-new-guinea", name: "Papua New Guinea", code: "PG" },
  { id: "paraguay", name: "Paraguay", code: "PY" },
  { id: "peru", name: "Peru", code: "PE" },
  { id: "philippines", name: "Philippines", code: "PH" },
  { id: "pitcairn", name: "Pitcairn", code: "PN" },
  { id: "poland", name: "Poland", code: "PL" },
  { id: "portugal", name: "Portugal", code: "PT" },
  { id: "puerto-rico", name: "Puerto Rico", code: "PR" },
  { id: "qatar", name: "Qatar", code: "QA" },
  { id: "romania", name: "Romania", code: "RO" },
  { id: "russian-federation", name: "Russian Federation", code: "RU" },
  { id: "rwanda", name: "Rwanda", code: "RW" },
  { id: "r-union", name: "Réunion", code: "RE" },
  { id: "saint-barth-lemy", name: "Saint Barthélemy", code: "BL" },
  { id: "saint-helena-ascension-and-tristan-da-cunha", name: "Saint Helena, Ascension and Tristan da Cunha", code: "SH" },
  { id: "saint-kitts-and-nevis", name: "Saint Kitts and Nevis", code: "KN" },
  { id: "saint-lucia", name: "Saint Lucia", code: "LC" },
  { id: "saint-martin-french-part", name: "Saint Martin (French part)", code: "MF" },
  { id: "saint-pierre-and-miquelon", name: "Saint Pierre and Miquelon", code: "PM" },
  { id: "saint-vincent-and-the-grenadines", name: "Saint Vincent and the Grenadines", code: "VC" },
  { id: "samoa", name: "Samoa", code: "WS" },
  { id: "san-marino", name: "San Marino", code: "SM" },
  { id: "sao-tome-and-principe", name: "Sao Tome and Principe", code: "ST" },
  { id: "saudi-arabia", name: "Saudi Arabia", code: "SA" },
  { id: "senegal", name: "Senegal", code: "SN" },
  { id: "serbia", name: "Serbia", code: "RS" },
  { id: "seychelles", name: "Seychelles", code: "SC" },
  { id: "sierra-leone", name: "Sierra Leone", code: "SL" },
  { id: "singapore", name: "Singapore", code: "SG" },
  { id: "sint-maarten-dutch-part", name: "Sint Maarten (Dutch part)", code: "SX" },
  { id: "slovakia", name: "Slovakia", code: "SK" },
  { id: "slovenia", name: "Slovenia", code: "SI" },
  { id: "solomon-islands", name: "Solomon Islands", code: "SB" },
  { id: "somalia", name: "Somalia", code: "SO" },
  { id: "south-africa", name: "South Africa", code: "ZA" },
  { id: "south-georgia-and-the-south-sandwich-islands", name: "South Georgia and the South Sandwich Islands", code: "GS" },
  { id: "south-sudan", name: "South Sudan", code: "SS" },
  { id: "spain", name: "Spain", code: "ES" },
  { id: "sri-lanka", name: "Sri Lanka", code: "LK" },
  { id: "sudan", name: "Sudan", code: "SD" },
  { id: "suriname", name: "Suriname", code: "SR" },
  { id: "svalbard-and-jan-mayen", name: "Svalbard and Jan Mayen", code: "SJ" },
  { id: "sweden", name: "Sweden", code: "SE" },
  { id: "switzerland", name: "Switzerland", code: "CH" },
  { id: "syria", name: "Syria", code: "SY" },
  { id: "taiwan", name: "Taiwan", code: "TW" },
  { id: "tajikistan", name: "Tajikistan", code: "TJ" },
  { id: "tanzania", name: "Tanzania", code: "TZ" },
  { id: "thailand", name: "Thailand", code: "TH" },
  { id: "timor-leste", name: "Timor-Leste", code: "TL" },
  { id: "togo", name: "Togo", code: "TG" },
  { id: "tokelau", name: "Tokelau", code: "TK" },
  { id: "tonga", name: "Tonga", code: "TO" },
  { id: "trinidad-and-tobago", name: "Trinidad and Tobago", code: "TT" },
  { id: "tunisia", name: "Tunisia", code: "TN" },
  { id: "turkmenistan", name: "Turkmenistan", code: "TM" },
  { id: "turks-and-caicos-islands", name: "Turks and Caicos Islands", code: "TC" },
  { id: "tuvalu", name: "Tuvalu", code: "TV" },
  { id: "t-rkiye", name: "Türkiye", code: "TR" },
  { id: "uganda", name: "Uganda", code: "UG" },
  { id: "ukraine", name: "Ukraine", code: "UA" },
  { id: "united-arab-emirates", name: "United Arab Emirates", code: "AE" },
  { id: "united-kingdom", name: "United Kingdom", code: "GB" },
  { id: "united-states", name: "United States", code: "US" },
  { id: "united-states-minor-outlying-islands", name: "United States Minor Outlying Islands", code: "UM" },
  { id: "uruguay", name: "Uruguay", code: "UY" },
  { id: "uzbekistan", name: "Uzbekistan", code: "UZ" },
  { id: "vanuatu", name: "Vanuatu", code: "VU" },
  { id: "venezuela", name: "Venezuela", code: "VE" },
  { id: "vietnam", name: "Vietnam", code: "VN" },
  { id: "virgin-islands-british", name: "Virgin Islands, British", code: "VG" },
  { id: "virgin-islands-u-s", name: "Virgin Islands, U.S.", code: "VI" },
  { id: "wallis-and-futuna", name: "Wallis and Futuna", code: "WF" },
  { id: "western-sahara", name: "Western Sahara", code: "EH" },
  { id: "yemen", name: "Yemen", code: "YE" },
  { id: "zambia", name: "Zambia", code: "ZM" },
  { id: "zimbabwe", name: "Zimbabwe", code: "ZW" },
  { id: "land-islands", name: "Åland Islands", code: "AX" },
];

export const COUNTRY_NAMES: readonly string[] = COUNTRY_CATALOG.map((c) => c.name);
