"use client";

import { useEffect } from "react";

export const TEXT_TRANSLATIONS: Record<string, string> = {
  "Administration Laawol Digital": "Administration Laawol Digital",
  "Action failed.": "L’action a échoué.",
  "Active": "Actif",
  "Active on public site": "Actif sur le site public",
  "Add": "Ajouter",
  "Add featured business": "Ajouter une entreprise mise en avant",
  "Add your first destination": "Ajouter votre première destination",
  "Add your first listing": "Ajouter votre première annonce",
  "Address": "Adresse",
  "Admin console": "Console admin",
  "All records": "Tous les dossiers",
  "All statuses": "Tous les statuts",
  "Analytics": "Analyses",
  "Apply": "Appliquer",
  "Approve extension": "Approuver la prolongation",
  "Approved": "Approuvé",
  "Approved featured businesses": "Entreprises mises en avant approuvées",
  "Available on the Pro plan — spots pricing, listing, and response issues and how to fix them.": "Disponible avec le forfait Pro : repère les problèmes de prix, d’annonces et de réponse, puis indique comment les corriger.",
  "Barrel shipments": "Expéditions de barils",
  "Barrel shipping": "Expédition de barils",
  "Barrels": "Barils",
  "Business": "Entreprise",
  "Business account is not configured.": "Le compte entreprise n’est pas configuré.",
  "Business dashboard": "Tableau de bord entreprise",
  "Business has consented to being featured": "L’entreprise a accepté d’être mise en avant",
  "Business name": "Nom de l’entreprise",
  "Business profile": "Profil de l’entreprise",
  "Buyer": "Acheteur",
  "Cancel": "Annuler",
  "Cancel & refund": "Annuler et rembourser",
  "Car parking": "Stationnement de voitures",
  "Car sales": "Vente de voitures",
  "Car transport": "Transport de voitures",
  "Choose a business": "Choisir une entreprise",
  "City": "Ville",
  "Clear": "Effacer",
  "Close": "Fermer",
  "Completed": "Terminé",
  "Contact": "Contact",
  "Contact email": "Email du contact",
  "Contact name": "Nom du contact",
  "Contact phone": "Téléphone du contact",
  "Country": "Pays",
  "Country pricing": "Prix par pays",
  "Create destination": "Créer la destination",
  "Create listing": "Créer l’annonce",
  "Create parking": "Créer le stationnement",
  "Create transport": "Créer le transport",
  "Created": "Créé",
  "Current plan": "Forfait actuel",
  "Customer purchases": "Achats clients",
  "Destination": "Destination",
  "Destinations": "Destinations",
  "Display name": "Nom public",
  "Download CSV": "Télécharger CSV",
  "Edit": "Modifier",
  "Edit featured business": "Modifier l’entreprise mise en avant",
  "Edit listing": "Modifier l’annonce",
  "Edit parking": "Modifier le stationnement",
  "Edit transport": "Modifier le transport",
  "Email": "Email",
  "Enabled services": "Services activés",
  "Export CSV": "Exporter CSV",
  "Export receipts": "Exporter les reçus",
  "Featured": "Mises en avant",
  "Featured max": "Maximum affiché",
  "Featured heading": "Titre des mises en avant",
  "Featured subheading": "Sous-titre des mises en avant",
  "Featuring requests": "Demandes de mise en avant",
  "Finance": "Finances",
  "Financing note": "Note de financement",
  "Free": "Gratuit",
  "Generate insights": "Générer les recommandations",
  "Growth": "Croissance",
  "Gross": "Brut",
  "Headline": "Titre",
  "Homepage cap": "Limite accueil",
  "Homepage content": "Contenu de l’accueil",
  "Hidden": "Masqué",
  "Hide": "Masquer",
  "Hold deposits": "Acomptes de blocage",
  "Hold until": "Blocage jusqu’au",
  "Inactive": "Inactif",
  "In transit": "En transit",
  "Listings": "Annonces",
  "Loading insights…": "Chargement des recommandations…",
  "Loading website content...": "Chargement du contenu du site...",
  "Logo URL": "URL du logo",
  "Make": "Marque",
  "Mark collected": "Marquer encaissé",
  "Mark sold": "Marquer vendu",
  "Message": "Message",
  "Model": "Modèle",
  "Needs action": "Action requise",
  "Not set": "Non défini",
  "New destination": "Nouvelle destination",
  "New listing": "Nouvelle annonce",
  "New parking": "Nouveau stationnement",
  "New transport": "Nouveau transport",
  "No AI insights yet": "Aucune recommandation IA pour le moment",
  "No destinations yet": "Aucune destination pour le moment",
  "No destinations match your search.": "Aucune destination ne correspond à votre recherche.",
  "No enabled services found.": "Aucun service activé trouvé.",
  "No featuring requests yet.": "Aucune demande de mise en avant pour le moment.",
  "No listings yet": "Aucune annonce pour le moment",
  "No listings match your search.": "Aucune annonce ne correspond à votre recherche.",
  "No parking records match this filter.": "Aucun dossier de stationnement ne correspond à ce filtre.",
  "No parked cars yet": "Aucune voiture stationnée pour le moment",
  "No purchases match this filter.": "Aucun achat ne correspond à ce filtre.",
  "No purchases yet": "Aucun achat pour le moment",
  "No rows loaded yet.": "Aucune ligne chargée pour le moment.",
  "No services are enabled yet.": "Aucun service n’est encore activé.",
  "No shipments match this filter.": "Aucune expédition ne correspond à ce filtre.",
  "No transport requests match this filter.": "Aucune demande de transport ne correspond à ce filtre.",
  "No transport requests yet": "Aucune demande de transport pour le moment",
  "Operations": "Opérations",
  "Operations mix": "Répartition des opérations",
  "Order": "Ordre",
  "Owner": "Propriétaire",
  "Parking": "Stationnement",
  "Page not found": "Page introuvable",
  "This page does not exist or has moved.": "Cette page n’existe pas ou a été déplacée.",
  "Back to console": "Retour à la console",
  "Parked cars": "Voitures stationnées",
  "Password": "Mot de passe",
  "Pending": "En attente",
  "Payment": "Paiement",
  "People": "Équipe",
  "Phone": "Téléphone",
  "Price": "Prix",
  "Price (USD)": "Prix (USD)",
  "Profile and services": "Profil et services",
  "Public website contact": "Contact du site public",
  "Publish": "Publier",
  "Purchases": "Achats",
  "Ready to publish.": "Prêt à publier.",
  "Reject": "Rejeter",
  "Remove": "Supprimer",
  "Requests": "Demandes",
  "Review": "Vérifier",
  "Save": "Enregistrer",
  "Save changes": "Enregistrer les modifications",
  "Save content": "Enregistrer le contenu",
  "Save featured": "Enregistrer la mise en avant",
  "Search": "Rechercher",
  "Select city": "Sélectionnez une ville",
  "Select color": "Sélectionnez une couleur",
  "Select condition": "Sélectionnez l’état",
  "Select country": "Sélectionnez un pays",
  "Select state": "Sélectionnez un État",
  "Select state first": "Sélectionnez d’abord un État",
  "Send": "Envoyer",
  "Services": "Services",
  "Services intro": "Introduction des services",
  "Settings": "Paramètres",
  "Show": "Afficher",
  "Show featured businesses": "Afficher les entreprises mises en avant",
  "Sign out": "Déconnexion",
  "Staff": "Personnel",
  "State": "État",
  "Status": "Statut",
  "Subheadline": "Sous-titre",
  "Support": "Assistance",
  "Support email": "Email d’assistance",
  "Support phone": "Téléphone d’assistance",
  "Sold": "Vendu",
  "Tools": "Outils",
  "Today": "Aujourd’hui",
  "Transport": "Transport",
  "Transport date": "Date de transport",
  "Upgrade to Pro": "Passer à Pro",
  "Upload logo": "Téléverser le logo",
  "View site": "Voir le site",
  "Website": "Site web",
  "Website URL": "URL du site web",
  "Year": "Année",
  "Unknown": "Inconnu",
  "Opening console...": "Ouverture de la console...",
  "Console Laawol Digital": "Console Laawol Digital",
  "Sign in to manage the platform or your business workspace.": "Connectez-vous pour gérer la plateforme ou l’espace de votre entreprise.",
  "Sign in": "Connexion",
  "Log in": "Se connecter",
  "Signing in...": "Connexion...",
  "Email or password is incorrect.": "L’email ou le mot de passe est incorrect.",
  "Too many attempts. Try again later.": "Trop de tentatives. Réessayez plus tard.",
  "Network error. Check your connection and try again.": "Erreur réseau. Vérifiez votre connexion et réessayez.",
  "Your account profile is missing. Contact platform support.": "Votre profil de compte est introuvable. Contactez l’assistance de la plateforme.",
  "This console is restricted to platform administrators, business owners, and business staff.": "Cette console est réservée aux administrateurs de la plateforme, aux propriétaires d’entreprise et au personnel d’entreprise.",
  "Access management": "Gestion des accès",
  "Access role": "Rôle d’accès",
  "Account settings": "Paramètres du compte",
  "Accounts by role": "Comptes par rôle",
  "Activate": "Activer",
  "Active listings": "Annonces actives",
  "Active destinations need a barrel shipping fee greater than 0.": "Les destinations actives doivent avoir un tarif d’expédition de baril supérieur à 0.",
  "Active (visible to customers)": "Actif (visible par les clients)",
  "Activity & requests": "Activité et demandes",
  "Add a car you're storing to start a parking record.": "Ajoutez une voiture que vous gardez pour créer un dossier de stationnement.",
  "Add a shipping price greater than zero before activating.": "Ajoutez un prix d’expédition supérieur à zéro avant d’activer.",
  "Add at least one photo.": "Ajoutez au moins une photo.",
  "Add country list": "Ajouter la liste des pays",
  "Add destination": "Ajouter une destination",
  "Add people": "Ajouter des personnes",
  "Add photos": "Ajouter des photos",
  "Add role": "Ajouter un rôle",
  "Add the countries you ship barrels to and set a price for each.": "Ajoutez les pays vers lesquels vous expédiez des barils et définissez un prix pour chacun.",
  "Add your first vehicle to start selling on the marketplace.": "Ajoutez votre premier véhicule pour commencer à vendre sur la marketplace.",
  "Admin profile": "Profil admin",
  "Admin role updated": "Rôle admin mis à jour",
  "Admin sections": "Sections admin",
  "Administrator": "Administrateur",
  "Admins": "Administrateurs",
  "Admins & customers": "Administrateurs et clients",
  "Admins assigned to it keep dashboard-only access until you reassign them.": "Les admins qui y sont affectés conservent un accès tableau de bord uniquement jusqu’à leur réaffectation.",
  "All business transactions": "Toutes les transactions d’entreprise",
  "All businesses": "Toutes les entreprises",
  "All service records": "Tous les dossiers de service",
  "All services": "Tous les services",
  "All sources": "Toutes les sources",
  "Allow reassignment of explicit IDs that already have a wrong/default businessId": "Autoriser la réaffectation des IDs explicites qui ont déjà un businessId incorrect ou par défaut",
  "Amount": "Montant",
  "Applicants must upload verification documents": "Les candidats doivent téléverser des documents de vérification",
  "Application rules saved": "Règles de candidature enregistrées",
  "Applications": "Candidatures",
  "Apply reviewed car IDs": "Appliquer les IDs de voitures vérifiés",
  "Appointment": "Rendez-vous",
  "Approved partners": "Partenaires approuvés",
  "Assign": "Attribuer",
  "Assign existing account…": "Attribuer un compte existant…",
  "Assign one owner for accountability.": "Attribuez un propriétaire responsable.",
  "Auto-approve new businesses": "Approuver automatiquement les nouvelles entreprises",
  "Awaiting partner approval": "En attente d’approbation du partenaire",
  "Balance due": "Solde dû",
  "Barrel and shared-load shipping with clear destination pricing.": "Expédition de barils et chargements partagés avec prix clairs par destination.",
  "Barrel shipment": "Expédition de baril",
  "Barrel shipment status emails": "Emails de statut d’expédition de baril",
  "Barrel shipping price must be zero or more.": "Le prix d’expédition de baril doit être égal ou supérieur à zéro.",
  "Barrels customers send through your business appear here.": "Les barils envoyés par les clients via votre entreprise apparaissent ici.",
  "Barrels, transport, parking": "Barils, transport, stationnement",
  "Shared barrel pool": "Baril partagé",
  "Shared barrel pools": "Barils partagés",
  "Shared barrel refund": "Remboursement de baril partagé",
  "Shared barrel refund due": "Remboursement de baril partagé à traiter",
  "Shared barrel balance": "Solde de baril partagé",
  "Shared barrel balance collected": "Solde de baril partagé encaissé",
  "Shared barrel balance collected.": "Solde de baril partagé encaissé.",
  "Shared barrel balance due": "Solde de baril partagé à encaisser",
  "Shared barrels": "Barils partagés",
  "Shared balances due": "Soldes partagés à encaisser",
  "Balance due amount": "Montant des soldes dus",
  "Blocked": "Bloqué",
  "Body": "Carrosserie",
  "Body type": "Type de carrosserie",
  "Branding saved": "Image de marque enregistrée",
  "Built-in": "Intégré",
  "Business application": "Candidature d’entreprise",
  "Business application requirements": "Exigences de candidature d’entreprise",
  "Business application waiting for review": "Candidature d’entreprise en attente d’examen",
  "Business destination list seeded": "Liste des destinations de l’entreprise initialisée",
  "Business for destination seed": "Entreprise pour l’initialisation des destinations",
  "Business head": "Responsable d’entreprise",
  "Business ID is required.": "L’ID de l’entreprise est requis.",
  "Business inventory": "Inventaire des entreprises",
  "Business listings": "Annonces de l’entreprise",
  "Business membership updated": "Adhésion à l’entreprise mise à jour",
  "Business network": "Réseau d’entreprises",
  "Business notification": "Notification d’entreprise",
  "Business people": "Équipe de l’entreprise",
  "Business profile created": "Profil d’entreprise créé",
  "Business profile was not found.": "Le profil de l’entreprise est introuvable.",
  "Business saved": "Entreprise enregistrée",
  "Business sections": "Sections de l’entreprise",
  "Business services": "Services de l’entreprise",
  "Business staff created": "Personnel d’entreprise créé",
  "Business status": "Statut de l’entreprise",
  "Business status updated": "Statut de l’entreprise mis à jour",
  "Business support request": "Demande d’assistance entreprise",
  "Business user": "Utilisateur entreprise",
  "Active inventory value": "Valeur du stock actif",
  "AI advisor + lower fees": "Conseiller IA + frais réduits",
  "Business AI advisor": "Conseiller IA entreprise",
  "Business contact not set": "Coordonnées non définies",
  "Could not generate recommendations.": "Impossible de générer les recommandations.",
  "Could not start payment.": "Impossible de démarrer le paiement.",
  "Critical": "Critique",
  "Finding:": "Constat :",
  "Generate new recommendations from your latest business data.": "Générez de nouvelles recommandations à partir des dernières données de votre entreprise.",
  "Generate recommendations": "Générer les recommandations",
  "Generate your first set of recommendations.": "Générez votre première série de recommandations.",
  "Get the AI advisor, deeper analytics, and reduced platform fees as you grow.": "Obtenez le conseiller IA, des analyses plus poussées et des frais de plateforme réduits pendant votre croissance.",
  "High": "Élevé",
  "Holds and buyers": "Blocages et acheteurs",
  "Included tools": "Outils inclus",
  "Laawol Digital Console": "Console Laawol Digital",
  "Listings, destinations, barrels, purchases, parking, transport, people, and support.": "Annonces, destinations, barils, achats, stationnement, transport, personnel et assistance.",
  "Low": "Faible",
  "Medium": "Moyen",
  "Needs attention": "À traiter",
  "No urgent operational items right now.": "Aucun point opérationnel urgent pour le moment.",
  "Open shipments": "Expéditions ouvertes",
  "Operational statuses": "Statuts opérationnels",
  "Owners and staff": "Propriétaires et personnel",
  "Payment session started.": "Session de paiement démarrée.",
  "Plan and AI advisor": "Forfait et conseiller IA",
  "Recommendations generated.": "Recommandations générées.",
  "Recommendation": "Recommandation",
  "Recommended action:": "Action recommandée :",
  "Requests and replies": "Demandes et réponses",
  "Shipping queue": "File d’expédition",
  "Stored cars": "Voitures stationnées",
  "Support requests": "Demandes d’assistance",
  "This account is not linked to a business.": "Ce compte n’est lié à aucune entreprise.",
  "This business is currently": "Cette entreprise est actuellement",
  "Upgrade to Pro to unlock the advisor.": "Passez à Pro pour débloquer le conseiller.",
  "Vehicle moves": "Déplacements de véhicules",
  "Vehicles for sale": "Voitures à vendre",
  "Workspace": "Espace de travail",
  "You can review setup data here while it waits for platform approval.": "Vous pouvez vérifier les données de configuration ici pendant l’attente d’approbation par la plateforme.",
  "Your included tools": "Vos outils inclus",
  "Your plan, benefits, and AI recommendations for your business.": "Votre forfait, vos avantages et les recommandations IA pour votre entreprise.",
  "active": "actif",
  "approved": "approuvé",
  "cancelled": "annulé",
  "closed": "fermé",
  "collected_by_business": "encaissé par l’entreprise",
  "completed": "terminé",
  "inactive": "inactif",
  "in_transit": "en transit",
  "pending": "en attente",
  "refund_pending": "remboursement en attente",
  "rejected": "rejeté",
  "reserved": "réservé",
  "resolved": "résolu",
  "sold": "vendu",
  "Businesses & applications": "Entreprises et candidatures",
  "Buyer phone": "Téléphone de l’acheteur",
  "Cancel &amp; refund": "Annuler et rembourser",
  "Cancelled": "Annulé",
  "Cancelled — deposit refund queued with the platform.": "Annulé : remboursement de l’acompte mis en file côté plateforme.",
  "Car make, model, and year are required.": "La marque, le modèle et l’année du véhicule sont requis.",
  "Car purchase": "Achat de voiture",
  "Car purchase status emails": "Emails de statut d’achat de voiture",
  "Car purchases": "Achats de voitures",
  "Card return": "Retour de carte",
  "Card return request": "Demande de retour de carte",
  "Card return requests": "Demandes de retour de carte",
  "Card returns": "Retours de carte",
  "Cars you list appear in the marketplace once approved.": "Les voitures que vous publiez apparaissent dans la marketplace après approbation.",
  "Cars, parking, transport, and shipping support for customers moving between the U.S. and West Africa.": "Voitures, stationnement, transport et expédition pour les clients entre les États-Unis et l’Afrique de l’Ouest.",
  "Cars, parking, transport, and shipping support for the road home.": "Voitures, stationnement, transport et expédition pour la route vers le pays.",
  "Cars, parking, transport, barrel shipping": "Voitures, stationnement, transport, expédition de barils",
  "Changes requested": "Modifications demandées",
  "Choose a business before sending.": "Choisissez une entreprise avant d’envoyer.",
  "Choose a business before uploading a logo.": "Choisissez une entreprise avant de téléverser un logo.",
  "Choose a business.": "Choisissez une entreprise.",
  "Choose at least one service for this business.": "Choisissez au moins un service pour cette entreprise.",
  "Choose business": "Choisir une entreprise",
  "City, state, ZIP": "Ville, État, code postal",
  "Clear filters": "Effacer les filtres",
  "Close account settings": "Fermer les paramètres du compte",
  "Closed": "Fermé",
  "Code": "Code",
  "Collection note (optional)": "Note d’encaissement (facultatif)",
  "Complete": "Terminer",
  "Completing refund request...": "Finalisation de la demande de remboursement...",
  "Condition": "État",
  "Configure how the console works. Create roles, decide what each one can see and do, and limit them to specific services.": "Configurez le fonctionnement de la console. Créez des rôles, décidez ce que chacun peut voir et faire, puis limitez-les à des services précis.",
  "Confirm": "Confirmer",
  "Confirm card return for RF-17": "Confirmer le retour de carte pour RF-17",
  "Confirmed": "Confirmé",
  "Confirming phone...": "Confirmation du téléphone...",
  "Contact only": "Contact uniquement",
  "Customer no-show": "Client absent",
  "Contact-only support references": "Références d’assistance contact uniquement",
  "Contacts": "Contacts",
  "Content manager": "Responsable du contenu",
  "Copied!": "Copié !",
  "Create": "Créer",
  "Create business": "Créer une entreprise",
  "Create business profile": "Créer le profil d’entreprise",
  "Create profile": "Créer le profil",
  "Create staff": "Créer le personnel",
  "Created from existing marketplace or operations records.": "Créé à partir des dossiers existants de marketplace ou d’opérations.",
  "Creating...": "Création...",
  "Customer accounts": "Comptes clients",
  "Customer email": "Email du client",
  "Customer name": "Nom du client",
  "Customer phone": "Téléphone du client",
  "Customer wallet balance": "Solde du portefeuille client",
  "Customers": "Clients",
  "Days": "Jours",
  "Deactivate": "Désactiver",
  "Default barrel price (USD)": "Prix de baril par défaut (USD)",
  "Default barrel pricing & destinations": "Prix de baril et destinations par défaut",
  "Default business migration complete": "Migration de l’entreprise par défaut terminée",
  "Delete": "Supprimer",
  "Delete role": "Supprimer le rôle",
  "Deleting...": "Suppression...",
  "Delivery": "Livraison",
  "Delivery days must be positive whole numbers, with max greater than or equal to min.": "Les jours de livraison doivent être des nombres entiers positifs, avec un maximum supérieur ou égal au minimum.",
  "Delivery estimate": "Estimation de livraison",
  "Delivery max (days)": "Livraison max (jours)",
  "Delivery min (days)": "Livraison min (jours)",
  "Delivered": "Livré",
  "Deposit": "Acompte",
  "Describe the request, what the customer needs, and any deadline.": "Décrivez la demande, le besoin du client et toute échéance.",
  "Describe the vehicle, history, condition, extras…": "Décrivez le véhicule, l’historique, l’état, les options…",
  "Description": "Description",
  "Destination activated.": "Destination activée.",
  "Destination business or country ID is missing.": "L’ID de l’entreprise ou du pays de destination est manquant.",
  "Destination countries": "Pays de destination",
  "Destination country seed complete": "Initialisation des pays de destination terminée",
  "Destination deactivated.": "Destination désactivée.",
  "Destination details": "Détails de destination",
  "Destination saved.": "Destination enregistrée.",
  "Destination updated": "Destination mise à jour",
  "Details": "Détails",
  "Disabled": "Désactivé",
  "Dismiss account settings": "Fermer les paramètres du compte",
  "Down": "Descendre",
  "Drivetrain": "Transmission motrice",
  "Draft": "Brouillon",
  "Drop-off": "Dépôt",
  "Dry run": "Simulation",
  "Edit public site copy and curate the small approved set of businesses shown on the marketing homepage.": "Modifiez le contenu du site public et sélectionnez le petit groupe d’entreprises approuvées affichées sur l’accueil marketing.",
  "Email not verified": "Email non vérifié",
  "Ended": "Terminé",
  "Enter a barrel shipping price greater than zero.": "Saisissez un prix d’expédition de baril supérieur à zéro.",
  "Enter a phone number first.": "Saisissez d’abord un numéro de téléphone.",
  "Enter a request message.": "Saisissez un message de demande.",
  "Enter a request subject.": "Saisissez un sujet de demande.",
  "Enter a title or make and model.": "Saisissez un titre ou une marque et un modèle.",
  "Enter a valid min/max delivery day range.": "Saisissez une plage de jours de livraison min/max valide.",
  "Enter a valid price.": "Saisissez un prix valide.",
  "Enter both min and max delivery days, or leave both empty.": "Saisissez les jours minimum et maximum, ou laissez les deux champs vides.",
  "Every queue is clear. Browse a business workspace to review activity.": "Toutes les files sont vides. Ouvrez un espace entreprise pour examiner l’activité.",
  "Every service request across all businesses, in one place. Pick a service to focus, or browse them all.": "Toutes les demandes de service de toutes les entreprises, au même endroit. Choisissez un service à examiner ou parcourez-les tous.",
  "Expired": "Expiré",
  "Explicit car IDs": "IDs de voitures explicites",
  "Extension approved.": "Prolongation approuvée.",
  "Extension rejected.": "Prolongation rejetée.",
  "Exterior": "Extérieur",
  "Exterior color": "Couleur extérieure",
  "Featured business published": "Entreprise mise en avant publiée",
  "Featured business removed": "Entreprise mise en avant supprimée",
  "Featured business updated": "Entreprise mise en avant mise à jour",
  "Featured order updated": "Ordre de mise en avant mis à jour",
  "Features": "Équipements",
  "Fee": "Frais",
  "Filtered": "Filtré",
  "Finance manager": "Responsable finance",
  "Finance queue": "File finance",
  "Find country": "Trouver un pays",
  "Find destination": "Trouver une destination",
  "Firebase Auth user listing is unavailable. Showing profile and activity records.": "La liste des utilisateurs Firebase Auth est indisponible. Affichage des profils et dossiers d’activité.",
  "Firebase SMS confirms this phone on the signed-in admin account.": "Firebase SMS confirme ce téléphone sur le compte admin connecté.",
  "Forfeited": "Confisqué",
  "Forfeiture": "Confiscation",
  "Fuel": "Carburant",
  "Fuel type": "Type de carburant",
  "Full": "Complet",
  "Global contacts": "Contacts globaux",
  "Halted": "Arrêté",
  "Hero eyebrow": "Surtitre du héros",
  "Hide details": "Masquer les détails",
  "Hold date reached — mark this vehicle sold, or mark the customer as a no-show.": "Date de blocage atteinte : marquez ce véhicule vendu ou marquez le client absent.",
  "Hold marked sold.": "Blocage marqué vendu.",
  "Hold pricing": "Prix de blocage",
  "Hold review required": "Vérification du blocage requise",
  "Holds, viewings, and buyers appear here as customers reserve your cars.": "Les blocages, visites et acheteurs apparaissent ici lorsque les clients réservent vos voitures.",
  "In progress": "En cours",
  "In review": "En examen",
  "Inferred from operational records": "Déduit des dossiers opérationnels",
  "Interior": "Intérieur",
  "Interior color": "Couleur intérieure",
  "Internal platform branding": "Image de marque interne de la plateforme",
  "Invalid email or password.": "Email ou mot de passe invalide.",
  "Ledger rows": "Lignes du registre",
  "Legacy business name": "Ancien nom d’entreprise",
  "Legacy car backfill applied": "Rattrapage des anciennes voitures appliqué",
  "Legacy car backfill dry run complete": "Simulation du rattrapage des anciennes voitures terminée",
  "Legacy car listing backfill": "Rattrapage des anciennes annonces de voitures",
  "Limited to services": "Limité aux services",
  "Listing sale state": "État de vente de l’annonce",
  "Listings by business": "Annonces par entreprise",
  "Loading...": "Chargement...",
  "Make and model": "Marque et modèle",
  "Manage": "Gérer",
  "Manage destinations": "Gérer les destinations",
  "Marketplace filters": "Filtres marketplace",
  "Marketplace listing": "Annonce marketplace",
  "Marketplace manager": "Responsable marketplace",
  "Mark customer no-show": "Marquer le client absent",
  "Mark hold sold": "Marquer le blocage vendu",
  "Marked no-show.": "Marqué absent.",
  "Message sent": "Message envoyé",
  "Mileage": "Kilométrage",
  "Monitor wallet balance return requests and finance readiness.": "Surveillez les demandes de retour de solde portefeuille et la préparation finance.",
  "Needs your attention": "Requiert votre attention",
  "Network": "Réseau",
  "Network health": "Santé du réseau",
  "New business application emails": "Emails de nouvelle candidature d’entreprise",
  "New role": "Nouveau rôle",
  "No barrel shipments yet": "Aucune expédition de baril pour le moment",
  "No shared barrel pools yet": "Aucun baril partagé pour le moment",
  "No shared barrel pools match this filter.": "Aucun baril partagé ne correspond à ce filtre.",
  "No business destination rows are loaded. Use Production tools to seed destinations for a business.": "Aucune ligne de destination d’entreprise n’est chargée. Utilisez les outils de production pour initialiser les destinations d’une entreprise.",
  "No business people assigned yet.": "Aucune personne d’entreprise affectée pour le moment.",
  "No business profiles are currently loaded.": "Aucun profil d’entreprise n’est actuellement chargé.",
  "No business support requests have been sent yet.": "Aucune demande d’assistance entreprise n’a encore été envoyée.",
  "No businesses loaded": "Aucune entreprise chargée",
  "No businesses match this search.": "Aucune entreprise ne correspond à cette recherche.",
  "No car listings are currently loaded.": "Aucune annonce de voiture n’est actuellement chargée.",
  "No card return requests for this business.": "Aucune demande de retour de carte pour cette entreprise.",
  "No refund requests for this business.": "Aucune demande de remboursement pour cette entreprise.",
  "No contact-only references match this search.": "Aucune référence contact uniquement ne correspond à cette recherche.",
  "No customer accounts match this search.": "Aucun compte client ne correspond à cette recherche.",
  "No customer contact": "Aucun contact client",
  "No default destinations yet.": "Aucune destination par défaut pour le moment.",
  "No delivery estimate": "Aucune estimation de livraison",
  "No destinations match this search.": "Aucune destination ne correspond à cette recherche.",
  "No email": "Aucun email",
  "No finance records are loaded yet.": "Aucun dossier financier n’est encore chargé.",
  "No finance rows match the current filters.": "Aucune ligne finance ne correspond aux filtres actuels.",
  "No legacy shipment pricing rows are loaded. Destination country coverage is shown on the right.": "Aucune ancienne ligne de prix d’expédition n’est chargée. La couverture des pays de destination est affichée à droite.",
  "No listings from this business match the current filters.": "Aucune annonce de cette entreprise ne correspond aux filtres actuels.",
  "No listings match the current marketplace filters.": "Aucune annonce ne correspond aux filtres marketplace actuels.",
  "No open approvals, shipments, purchases, or refunds are currently loaded.": "Aucune approbation, expédition, achat ou remboursement ouvert n’est actuellement chargé.",
  "No owner assigned": "Aucun propriétaire affecté",
  "No phone": "Aucun téléphone",
  "No photo": "Aucune photo",
  "No platform administrators match this search.": "Aucun administrateur de plateforme ne correspond à cette recherche.",
  "No public featured businesses have been approved yet.": "Aucune entreprise publique mise en avant n’a encore été approuvée.",
  "No records": "Aucun dossier",
  "No records match the current filters.": "Aucun dossier ne correspond aux filtres actuels.",
  "No records yet": "Aucun dossier pour le moment",
  "No related business records are currently loaded.": "Aucun dossier d’entreprise associé n’est actuellement chargé.",
  "No service records are currently loaded.": "Aucun dossier de service n’est actuellement chargé.",
  "No show": "Absent",
  "No staff assigned.": "Aucun membre du personnel affecté.",
  "No wallet account loaded": "Aucun compte portefeuille chargé",
  "No wallet card return requests are loaded.": "Aucune demande de retour de carte portefeuille n’est chargée.",
  "No-show": "Absence",
  "None": "Aucun",
  "Not confirmed": "Non confirmé",
  "Not required": "Non requis",
  "Not requested": "Non demandé",
  "Note for customers (optional)": "Note pour les clients (facultatif)",
  "Notification preferences saved": "Préférences de notification enregistrées",
  "Notifications & email preferences": "Notifications et préférences email",
  "Notify admins of new applications": "Notifier les admins des nouvelles candidatures",
  "Open": "Ouvert",
  "Open pooled barrels, approve joiners, and seal full barrels into tracked shipments.": "Ouvrez des barils groupés, approuvez les participants et scellez les barils complets en expéditions suivies.",
  "Open account settings": "Ouvrir les paramètres du compte",
  "Open application": "Ouvrir la candidature",
  "Open by status": "Ouverts par statut",
  "Open console": "Ouvrir la console",
  "Open purchase": "Ouvrir l’achat",
  "Open shipment": "Ouvrir l’expédition",
  "Opening admin console...": "Ouverture de la console admin...",
  "Operations manager": "Responsable opérations",
  "Optional": "Facultatif",
  "Optional old display name": "Ancien nom public facultatif",
  "Overview": "Vue d’ensemble",
  "Owner email": "Email du propriétaire",
  "Owner name": "Nom du propriétaire",
  "Owner name is required.": "Le nom du propriétaire est requis.",
  "Owner phone": "Téléphone du propriétaire",
  "Owners": "Propriétaires",
  "Paid hold": "Blocage payé",
  "Paid holds": "Blocages payés",
  "Paid": "Payé",
  "Parked": "Stationné",
  "Parked car": "Voiture stationnée",
  "Parking date": "Date de stationnement",
  "Parking record created.": "Dossier de stationnement créé.",
  "Parking record updated.": "Dossier de stationnement mis à jour.",
  "Parking status updated.": "Statut de stationnement mis à jour.",
  "Partner workspaces": "Espaces partenaires",
  "Payments": "Paiements",
  "Pending amount": "Montant en attente",
  "Pending document review": "Vérification des documents en attente",
  "Pending in wallets": "En attente dans les portefeuilles",
  "Pending payment": "Paiement en attente",
  "Pending purchases": "Achats en attente",
  "Pending refund amount": "Montant de remboursement en attente",
  "Pending refunds": "Remboursements en attente",
  "Pending return": "Retour en attente",
  "Pending seal": "En attente de scellement",
  "People & access": "Équipe et accès",
  "Per day": "Par jour",
  "Partially filled": "Partiellement rempli",
  "Phone confirmation": "Confirmation du téléphone",
  "Phone confirmed": "Téléphone confirmé",
  "Phone verification code sent": "Code de vérification téléphone envoyé",
  "Photo URL": "URL de la photo",
  "Pick a partner to manage its people, listings, services, payments, and support history in one place.": "Choisissez un partenaire pour gérer son équipe, ses annonces, ses services, ses paiements et son historique d’assistance au même endroit.",
  "Pick-up": "Collecte",
  "Pickup": "Collecte",
  "Pickup address": "Adresse de collecte",
  "Pickup borough": "Arrondissement de collecte",
  "Pickup fee": "Frais de collecte",
  "Pickup time": "Heure de collecte",
  "Platform Administrator": "Administrateur de plateforme",
  "Platform admins": "Administrateurs plateforme",
  "Platform manager": "Responsable plateforme",
  "Platform manager created": "Responsable plateforme créé",
  "Platform name": "Nom de la plateforme",
  "Preview Administrator": "Aperçu administrateur",
  "Preview data": "Données d’aperçu",
  "Price is negotiable": "Prix négociable",
  "Price per barrel (USD)": "Prix par baril (USD)",
  "Pricing &amp; status": "Prix et statut",
  "Pricing is pending review for this shipment.": "Le prix de cette expédition est en attente d’examen.",
  "Pricing rows": "Lignes de prix",
  "Primary CTA href": "Lien du CTA principal",
  "Primary CTA label": "Libellé du CTA principal",
  "Priority": "Priorité",
  "Production console for platform administrators.": "Console de production pour les administrateurs de plateforme.",
  "Production setup tools": "Outils de configuration production",
  "Production tools": "Outils production",
  "Profile only": "Profil uniquement",
  "Profile photo": "Photo de profil",
  "Profile photo uploaded": "Photo de profil téléversée",
  "Profile updated": "Profil mis à jour",
  "Ready to review": "Prêt à examiner",
  "Ready for pickup": "Prêt pour collecte",
  "Receiver": "Destinataire",
  "Receiver name": "Nom du destinataire",
  "Receiver phone": "Téléphone du destinataire",
  "Recent activity": "Activité récente",
  "Recent business support requests": "Demandes récentes d’assistance entreprise",
  "Record": "Dossier",
  "Records": "Dossiers",
  "Refresh": "Actualiser",
  "Refresh Auth": "Actualiser Auth",
  "Refund decision emails": "Emails de décision de remboursement",
  "Refund queue": "File de remboursements",
  "Refund request": "Demande de remboursement",
  "Refund request completed": "Demande de remboursement terminée",
  "Refund request rejected": "Demande de remboursement rejetée",
  "Refund requests": "Demandes de remboursement",
  "Refund pending": "Remboursement en attente",
  "Refunded": "Remboursé",
  "Refunds": "Remboursements",
  "Refunds to pay": "Remboursements à payer",
  "Rejecting refund request...": "Rejet de la demande de remboursement...",
  "Related:": "Associé :",
  "Remove to customer": "Retourner au client",
  "Reply to support requests": "Répondre aux demandes d’assistance",
  "Request amount": "Montant demandé",
  "Requested": "Demandé",
  "All pool statuses": "Tous les statuts de baril partagé",
  "Add an active barrel destination with a price before starting a shared pool.": "Ajoutez une destination de baril active avec un prix avant d’ouvrir un baril partagé.",
  "Adjusted total shares cannot be below reserved shares.": "Le total ajusté ne peut pas être inférieur aux parts réservées.",
  "Adjusted total shares must be between 2 and 4.": "Le total ajusté des parts doit être entre 2 et 4.",
  "Adjust inspected shares": "Ajuster les parts inspectées",
  "Adjust shares": "Ajuster les parts",
  "Air": "Aérien",
  "Approve": "Approuver",
  "Approval mode": "Mode d’approbation",
  "Auto approve": "Approbation automatique",
  "Business-held": "Géré par l’entreprise",
  "Business payout": "Versement entreprise",
  "Choose a shared barrel pool.": "Choisissez un baril partagé.",
  "Choose a destination.": "Choisissez une destination.",
  "Contents note": "Note sur le contenu",
  "Current shares": "Parts actuelles",
  "Customer drop-off": "Dépôt client",
  "Customer-posted, drop-off, and business-held consolidation pools will appear here.": "Les regroupements publiés par les clients, déposés ou gérés par l’entreprise apparaîtront ici.",
  "Drop-off pools need 1 reserved share and at least 1 open share.": "Les barils déposés nécessitent 1 part réservée et au moins 1 part ouverte.",
  "Enter at least 1 max joiner.": "Saisissez au moins 1 participant maximum.",
  "Explain measured capacity or packing mismatch": "Expliquez la capacité mesurée ou l’écart de chargement",
  "Inspected total shares": "Total des parts inspectées",
  "Inspection note": "Note d’inspection",
  "Inspection note is required.": "La note d’inspection est requise.",
  "Inspection note:": "Note d’inspection :",
  "Joiner accepted.": "Participant accepté.",
  "Joiner rejected.": "Participant rejeté.",
  "Join deadline": "Date limite d’inscription",
  "Last inspection": "Dernière inspection",
  "Manual approval": "Approbation manuelle",
  "Max joiners": "Participants max.",
  "Open pool": "Ouvrir le baril",
  "Optional packing note": "Note de colis facultative",
  "Only active shared barrel pools can be adjusted.": "Seuls les barils partagés actifs peuvent être ajustés.",
  "Pool capacity adjusted.": "Capacité du baril ajustée.",
  "Pool cancelled.": "Baril partagé annulé.",
  "Pool is required.": "Le baril partagé est requis.",
  "Pool origin": "Origine du baril",
  "Recipient name": "Nom du destinataire",
  "Reserved shares": "Parts réservées",
  "Reserved shares must leave at least 1 share open.": "Les parts réservées doivent laisser au moins 1 part ouverte.",
  "Pool sealed into a shipment.": "Baril scellé en expédition.",
  "Platform fee": "Frais plateforme",
  "Sender, receiver, and receiver phone are required for drop-off pools.": "L’expéditeur, le destinataire et le téléphone du destinataire sont requis pour les dépôts client.",
  "Sender name": "Nom de l’expéditeur",
  "Save adjustment": "Enregistrer l’ajustement",
  "Seal pool": "Sceller le baril",
  "Seal underfilled": "Sceller partiellement",
  "Sealed": "Scellé",
  "Sea": "Maritime",
  "Ship mode": "Mode d’expédition",
  "Shared barrel pool opened.": "Baril partagé ouvert.",
  "Start pool": "Ouvrir un baril",
  "Start shared barrel pool": "Ouvrir un baril partagé",
  "Total shares": "Nombre total de parts",
  "Total shares must be between 2 and 4.": "Le nombre total de parts doit être entre 2 et 4.",
  "Underfilled": "Partiellement rempli",
  "Underfilled pool sealed into a shipment.": "Baril partiellement rempli scellé en expédition.",
  "Update total shares only after physical inspection. The total cannot be lower than already reserved shares.": "Ajustez le nombre total de parts seulement après inspection physique. Le total ne peut pas être inférieur aux parts déjà réservées.",
  "2 halves": "2 moitiés",
  "3 shares": "3 parts",
  "4 quarters": "4 quarts",
  "Require at least one service": "Exiger au moins un service",
  "Require business address": "Exiger l’adresse de l’entreprise",
  "Require business documents": "Exiger les documents de l’entreprise",
  "Require phone number": "Exiger le numéro de téléphone",
  "Resolve refund": "Résoudre le remboursement",
  "Return this pending amount to the customer's wallet?": "Retourner ce montant en attente dans le portefeuille du client ?",
  "Review business": "Examiner l’entreprise",
  "Review each business first, then inspect and control the listings that business published.": "Examinez d’abord chaque entreprise, puis inspectez et contrôlez les annonces qu’elle a publiées.",
  "Review note": "Note d’examen",
  "Review the customer account and wallet balance before action. Complete after the external card return is done. Reject moves the pending amount back to the customer's wallet.": "Examinez le compte client et le solde du portefeuille avant d’agir. Terminez après le retour externe de la carte. Le rejet remet le montant en attente dans le portefeuille du client.",
  "Reviewed": "Examiné",
  "Role name": "Nom du rôle",
  "Roles": "Rôles",
  "Roles & configuration": "Rôles et configuration",
  "Roles & permissions": "Rôles et permissions",
  "Roles & permissions saved": "Rôles et permissions enregistrés",
  "Run a dry run or enter explicit car IDs before applying.": "Lancez une simulation ou saisissez des IDs de voitures explicites avant d’appliquer.",
  "Run setup utilities that already exist in the Firebase backend.": "Lancez les utilitaires de configuration déjà présents dans le backend Firebase.",
  "Running...": "Exécution...",
  "Sales contact": "Contact vente",
  "Saved": "Enregistré",
  "Saving profile...": "Enregistrement du profil...",
  "Saving...": "Enregistrement...",
  "Schedule a vehicle transport to get started.": "Planifiez un transport de véhicule pour commencer.",
  "Schedule and track car transport for your customers.": "Planifiez et suivez le transport de voitures pour vos clients.",
  "Scheduled": "Planifié",
  "Search businesses": "Rechercher des entreprises",
  "Search customer, business, phone, tracking, status": "Rechercher client, entreprise, téléphone, suivi, statut",
  "Search records": "Rechercher des dossiers",
  "Search title, VIN, stock, make, contact": "Rechercher titre, VIN, stock, marque, contact",
  "Search users": "Rechercher des utilisateurs",
  "Secondary CTA href": "Lien du CTA secondaire",
  "Secondary CTA label": "Libellé du CTA secondaire",
  "Seed selected business destinations": "Initialiser les destinations de l’entreprise sélectionnée",
  "Select a business first.": "Sélectionnez d’abord une entreprise.",
  "Select a business to open its workspace.": "Sélectionnez une entreprise pour ouvrir son espace.",
  "Select a destination country.": "Sélectionnez un pays de destination.",
  "Select a supported country.": "Sélectionnez un pays pris en charge.",
  "Select at least one listing.": "Sélectionnez au moins une annonce.",
  "Select body type": "Sélectionner le type de carrosserie",
  "Select drivetrain": "Sélectionner la transmission motrice",
  "Select fuel type": "Sélectionner le carburant",
  "Select transmission": "Sélectionner la transmission",
  "Send a code and enter it before confirming.": "Envoyez un code et saisissez-le avant de confirmer.",
  "Send code": "Envoyer le code",
  "Sender": "Expéditeur",
  "Sender address": "Adresse de l’expéditeur",
  "Sender email": "Email de l’expéditeur",
  "Sender phone": "Téléphone de l’expéditeur",
  "Sending phone code...": "Envoi du code téléphone...",
  "Service load": "Charge de service",
  "Service operations": "Opérations de service",
  "Service types": "Types de service",
  "Set a price per country so customers can ship barrels there.": "Définissez un prix par pays afin que les clients puissent y envoyer des barils.",
  "Set as cover": "Définir comme couverture",
  "Setup utilities": "Utilitaires de configuration",
  "Shipment pricing": "Prix d’expédition",
  "Shipment updated.": "Expédition mise à jour.",
  "Shipments": "Expéditions",
  "Shipping defaults saved": "Paramètres d’expédition par défaut enregistrés",
  "Shipping destinations": "Destinations d’expédition",
  "Shipping fee": "Frais d’expédition",
  "Showing": "Affichage",
  "Sign in before confirming your phone.": "Connectez-vous avant de confirmer votre téléphone.",
  "Sign in before uploading a profile photo.": "Connectez-vous avant de téléverser une photo de profil.",
  "Sign in failed. Try again or contact support.": "Connexion échouée. Réessayez ou contactez l’assistance.",
  "Signed in": "Connecté",
  "Site content": "Contenu du site",
  "Skip manual review (not recommended)": "Ignorer l’examen manuel (non recommandé)",
  "SMS code": "Code SMS",
  "Sold amount": "Montant vendu",
  "Sold date": "Date de vente",
  "Sold email": "Email de vente",
  "Sold notes": "Notes de vente",
  "Sold phone": "Téléphone de vente",
  "Sold to": "Vendu à",
  "Specifications": "Caractéristiques",
  "Status updated.": "Statut mis à jour.",
  "Stock": "Stock",
  "Stock number": "Numéro de stock",
  "Street address (optional)": "Adresse (facultatif)",
  "Subject": "Sujet",
  "Super admin": "Super admin",
  "Support admin": "Admin assistance",
  "Support contacts": "Contacts d’assistance",
  "Support request": "Demande d’assistance",
  "Support request sent": "Demande d’assistance envoyée",
  "Suspended": "Suspendu",
  "System": "Système",
  "Tagline": "Slogan",
  "Team": "Équipe",
  "These fields are public. Keep private platform settings in Settings; only marketing-safe contact details belong here.": "Ces champs sont publics. Gardez les paramètres privés de plateforme dans Paramètres; seuls les contacts adaptés au marketing doivent figurer ici.",
  "These people were found on shipments, purchases, refunds, or service records. They are not editable accounts unless Firebase Auth has a matching user.": "Ces personnes ont été trouvées dans des expéditions, achats, remboursements ou dossiers de service. Ce ne sont pas des comptes modifiables sauf si Firebase Auth possède un utilisateur correspondant.",
  "These settings stay in the admin and app configuration. Public website copy and marketing contact details are managed from Website.": "Ces paramètres restent dans la configuration admin et app. Le contenu du site public et les contacts marketing sont gérés dans Site web.",
  "This business has no destination list yet. Add the country list, then activate only the countries this business ships to.": "Cette entreprise n’a pas encore de liste de destinations. Ajoutez la liste des pays, puis activez uniquement ceux desservis par cette entreprise.",
  "This business has no marketplace listings loaded.": "Aucune annonce marketplace n’est chargée pour cette entreprise.",
  "This business was inferred from existing marketplace or operations records. Create a profile document before assigning people or editing status.": "Cette entreprise a été déduite de dossiers marketplace ou opérationnels existants. Créez un document de profil avant d’affecter des personnes ou de modifier le statut.",
  "This console is restricted to platform administrators.": "Cette console est réservée aux administrateurs de la plateforme.",
  "This role can view finance records but cannot send business support requests.": "Ce rôle peut voir les dossiers financiers mais ne peut pas envoyer de demandes d’assistance entreprise.",
  "Title": "Titre",
  "Too many failed attempts. Try again later.": "Trop de tentatives échouées. Réessayez plus tard.",
  "Total": "Total",
  "Total cost": "Coût total",
  "Total cost (USD)": "Coût total (USD)",
  "Total records": "Total des dossiers",
  "Tracking code": "Code de suivi",
  "Transmission": "Transmission",
  "Transport created.": "Transport créé.",
  "Transport request": "Demande de transport",
  "Transport requests": "Demandes de transport",
  "Transport updated.": "Transport mis à jour.",
  "Trusted services from registered businesses": "Services de confiance proposés par des entreprises inscrites",
  "Unassigned business": "Entreprise non affectée",
  "Unassigned listings": "Annonces non affectées",
  "Unsaved": "Non enregistré",
  "Untitled role": "Rôle sans titre",
  "Up": "Monter",
  "Update failed.": "Échec de la mise à jour.",
  "Update status": "Mettre à jour le statut",
  "Updated": "Mis à jour",
  "Updated by": "Mis à jour par",
  "Updating destination...": "Mise à jour de la destination...",
  "Updating...": "Mise à jour...",
  "Upload photo": "Téléverser une photo",
  "Uploading photo...": "Téléversement de la photo...",
  "Uploading...": "Téléversement...",
  "Used in the admin header and audit/account context.": "Utilisé dans l’en-tête admin et le contexte audit/compte.",
  "User deleted": "Utilisateur supprimé",
  "User profile created": "Profil utilisateur créé",
  "User role updated": "Rôle utilisateur mis à jour",
  "Vehicle": "Véhicule",
  "Vehicle transport": "Transport de véhicule",
  "View": "Voir",
  "View only": "Lecture seule",
  "Viewing": "Visite",
  "Viewing scheduled": "Visite planifiée",
  "Viewings": "Visites",
  "Wallet balance": "Solde portefeuille",
  "Wallet card return requests": "Demandes de retour de carte portefeuille",
  "Wallet transaction": "Transaction portefeuille",
  "Website contact saved": "Contact du site enregistré",
  "Website content saved": "Contenu du site enregistré",
  "What needs you now": "Ce qui vous attend maintenant",
  "What should the business handle?": "Que doit gérer l’entreprise ?",
  "WhatsApp": "WhatsApp",
  "When customers book barrels to your destinations, they show up here to manage.": "Lorsque les clients réservent des barils vers vos destinations, ils apparaissent ici pour gestion.",
  "When customers reserve a viewing or pay a hold deposit, they show up here.": "Lorsque les clients réservent une visite ou paient un acompte de blocage, ils apparaissent ici.",
  "Wrong/default ownership fixes require explicit car IDs.": "Les corrections de propriété incorrecte/par défaut exigent des IDs de voitures explicites.",
  "You have view access to people. Managing administrators, roles, and accounts requires the Super admin or User-management privilege.": "Vous avez un accès en lecture à l’équipe. La gestion des administrateurs, rôles et comptes exige le privilège Super admin ou Gestion utilisateurs.",
  "Your listings": "Vos annonces",
  "ZIP / postal code": "Code postal",
  "/ barrel": "/ baril",
  "Senegal": "Sénégal",
  "Confirm contents, prohibited items, and shared liability before starting the pool.": "Confirmez le contenu, les articles interdits et la responsabilité partagée avant d’ouvrir le baril.",
  "Contents note is required for drop-off pools.": "La note de contenu est requise pour les barils déposés.",
  "Contents and weight were reviewed with the customer.": "Le contenu et le poids ont été vérifiés avec le client.",
  "Describe packed contents": "Décrivez le contenu emballé",
  "Drop-off weight must fit the reserved shares.": "Le poids du dépôt doit correspondre aux parts réservées.",
  "Inspected weight (kg)": "Poids inspecté (kg)",
  "No prohibited or unsafe items were accepted.": "Aucun article interdit ou dangereux n’a été accepté.",
  "The customer accepted shared-barrel liability and inspection rules.": "Le client a accepté la responsabilité du baril partagé et les règles d’inspection.",
  "20 kg per share max": "20 kg maximum par part",
};

const ATTRIBUTE_TRANSLATIONS: Record<string, string> = {
  "Add a photo by URL": "Ajouter une photo par URL",
  "Collapse navigation": "Réduire la navigation",
  "Copy tracking code": "Copier le code de suivi",
  "Expand navigation": "Développer la navigation",
  "No-show note (optional)": "Note d’absence (facultatif)",
  "Search car, buyer, phone, status…": "Rechercher voiture, acheteur, téléphone, statut…",
  "Search destinations…": "Rechercher des destinations…",
  "Search make, model, status…": "Rechercher marque, modèle, statut…",
  "Search tracking, owner, car, VIN…": "Rechercher suivi, propriétaire, voiture, VIN…",
  "Search tracking, sender, receiver, phone…": "Rechercher suivi, expéditeur, destinataire, téléphone…",
  "Signed-in account": "Compte connecté",
};

const STORAGE_KEY = "laawol:lang";
const frToEn = Object.entries(TEXT_TRANSLATIONS).reduce<Record<string, string>>(
  (result, [english, french]) => {
    result[french] = english;
    return result;
  },
  {},
);
const attrFrToEn = Object.entries(ATTRIBUTE_TRANSLATIONS).reduce<Record<string, string>>(
  (result, [english, french]) => {
    result[french] = english;
    return result;
  },
  {},
);
const englishDictionary = { ...TEXT_TRANSLATIONS, ...ATTRIBUTE_TRANSLATIONS };
const frenchDictionary = { ...frToEn, ...attrFrToEn };
const englishTextKeys = Object.keys(englishDictionary).sort((a, b) => b.length - a.length);
const frenchTextKeys = Object.keys(frenchDictionary).sort((a, b) => b.length - a.length);

// Precompile a single alternation regex per direction instead of running a
// ~600-key `replaceAll` reduce on every text node. Keys are sorted
// longest-first, and regex alternation takes the first matching branch at each
// position, so longer phrases win — preserving longest-match behaviour in one
// pass. Without this, translating the full admin DOM pegs the main thread.
function buildTranslationRegex(keys: string[]) {
  if (keys.length === 0) return null;
  const escaped = keys.map((key) => key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"));
  return new RegExp(escaped.join("|"), "g");
}
const englishRegex = buildTranslationRegex(englishTextKeys);
const frenchRegex = buildTranslationRegex(frenchTextKeys);

function currentLang() {
  if (typeof window === "undefined") return "fr";
  return window.localStorage.getItem(STORAGE_KEY) === "en" ? "en" : "fr";
}

export function translateValue(value: string, lang: string) {
  const sourceDict = lang === "en" ? frenchDictionary : englishDictionary;
  const exact = sourceDict[value];
  if (exact) return exact;

  // Already in the target language? A known translated value (e.g. "Finances")
  // must be returned untouched — otherwise the substring regex re-translates a
  // fragment of it ("Finance" -> "Finances" -> "Financess" -> …) and never
  // converges. This keeps translation idempotent by construction.
  const targetDict = lang === "en" ? englishDictionary : frenchDictionary;
  if (value in targetDict) return value;

  const regex = lang === "en" ? frenchRegex : englishRegex;
  if (!regex) return value;
  regex.lastIndex = 0;
  return value.replace(regex, (match) => sourceDict[match] ?? match);
}

function translateTextNode(node: Node) {
  const value = node.textContent;
  if (!value) return;
  const trimmed = value.trim();
  const translated = translateValue(trimmed, currentLang());
  if (translated === trimmed) return;
  node.textContent = value.replace(trimmed, translated);
}

function translateAttributes(element: Element) {
  ["placeholder", "title", "aria-label", "alt"].forEach((name) => {
    const value = element.getAttribute(name);
    if (!value) return;
    const translated = translateValue(value, currentLang());
    if (translated !== value) element.setAttribute(name, translated);
  });
}

function translateTree(root: ParentNode) {
  const walker = document.createTreeWalker(root, NodeFilter.SHOW_TEXT);
  let current = walker.nextNode();
  while (current) {
    translateTextNode(current);
    current = walker.nextNode();
  }
  if (root instanceof Element) translateAttributes(root);
  root.querySelectorAll?.("*").forEach(translateAttributes);
  document.documentElement.lang = currentLang();
  document.title = translateValue(document.title, currentLang());
}

function installToggle() {
  if (document.querySelector("[data-console-lang-toggle]")) return;
  const button = document.createElement("button");
  button.type = "button";
  button.className = "secondary-button compact";
  button.dataset.consoleLangToggle = "true";
  button.textContent = currentLang() === "en" ? "Français" : "English";
  button.style.position = "fixed";
  button.style.right = "16px";
  button.style.bottom = "16px";
  button.style.zIndex = "1000";
  button.addEventListener("click", () => {
    window.localStorage.setItem(STORAGE_KEY, currentLang() === "en" ? "fr" : "en");
    window.location.reload();
  });
  document.body.appendChild(button);
}

export function useFrenchDomTranslation() {
  useEffect(() => {
    installToggle();

    let observer: MutationObserver | null = null;
    // Guard against the observer reacting to its own DOM writes. Writing
    // `textContent`/attributes triggers more mutations; without this the
    // observer feeds itself in an endless loop and freezes the console.
    let translating = false;
    const runGuarded = (work: () => void) => {
      if (translating) return;
      translating = true;
      try {
        work();
      } finally {
        // Discard the mutation records our own writes just generated so they
        // are not reprocessed when the next callback fires.
        observer?.takeRecords();
        translating = false;
      }
    };

    runGuarded(() => translateTree(document.body));

    observer = new MutationObserver((mutations) => {
      runGuarded(() => {
        for (const mutation of mutations) {
          mutation.addedNodes.forEach((node) => {
            if (node.nodeType === Node.TEXT_NODE) {
              translateTextNode(node);
            } else if (node instanceof Element) {
              translateTree(node);
            }
          });
          if (mutation.type === "characterData") translateTextNode(mutation.target);
        }
      });
    });
    observer.observe(document.body, { childList: true, characterData: true, subtree: true });
    return () => observer?.disconnect();
  }, []);
}
