// AUTO-PORTED from my_flutter_app/lib/data/us_locations.dart — full US states + cities.
// Keep in sync with the mobile app so web listings capture the same location data.

export const US_STATE_NAMES: Record<string, string> = {
  'AL': 'Alabama',
  'AK': 'Alaska',
  'AZ': 'Arizona',
  'AR': 'Arkansas',
  'CA': 'California',
  'CO': 'Colorado',
  'CT': 'Connecticut',
  'DE': 'Delaware',
  'FL': 'Florida',
  'GA': 'Georgia',
  'HI': 'Hawaii',
  'ID': 'Idaho',
  'IL': 'Illinois',
  'IN': 'Indiana',
  'IA': 'Iowa',
  'KS': 'Kansas',
  'KY': 'Kentucky',
  'LA': 'Louisiana',
  'ME': 'Maine',
  'MD': 'Maryland',
  'MA': 'Massachusetts',
  'MI': 'Michigan',
  'MN': 'Minnesota',
  'MS': 'Mississippi',
  'MO': 'Missouri',
  'MT': 'Montana',
  'NE': 'Nebraska',
  'NV': 'Nevada',
  'NH': 'New Hampshire',
  'NJ': 'New Jersey',
  'NM': 'New Mexico',
  'NY': 'New York',
  'NC': 'North Carolina',
  'ND': 'North Dakota',
  'OH': 'Ohio',
  'OK': 'Oklahoma',
  'OR': 'Oregon',
  'PA': 'Pennsylvania',
  'RI': 'Rhode Island',
  'SC': 'South Carolina',
  'SD': 'South Dakota',
  'TN': 'Tennessee',
  'TX': 'Texas',
  'UT': 'Utah',
  'VT': 'Vermont',
  'VA': 'Virginia',
  'WA': 'Washington',
  'WV': 'West Virginia',
  'WI': 'Wisconsin',
  'WY': 'Wyoming',
  'DC': 'District of Columbia',
};

export const CITIES_BY_STATE: Record<string, string[]> = {
  'AL': [
    'Birmingham',
    'Montgomery',
    'Huntsville',
    'Mobile',
    'Tuscaloosa',
    'Hoover',
    'Auburn',
    'Dothan',
  ],
  'AK': [
    'Anchorage',
    'Fairbanks',
    'Juneau',
    'Wasilla',
    'Sitka',
    'Ketchikan',
    'Kenai',
    'Kodiak',
  ],
  'AZ': [
    'Phoenix',
    'Tucson',
    'Mesa',
    'Chandler',
    'Scottsdale',
    'Glendale',
    'Gilbert',
    'Tempe',
  ],
  'AR': [
    'Little Rock',
    'Fort Smith',
    'Fayetteville',
    'Springdale',
    'Jonesboro',
    'Rogers',
    'Conway',
    'Bentonville',
  ],
  'CA': [
    'Los Angeles',
    'San Diego',
    'San Jose',
    'San Francisco',
    'Sacramento',
    'Fresno',
    'Long Beach',
    'Oakland',
  ],
  'CO': [
    'Denver',
    'Colorado Springs',
    'Aurora',
    'Fort Collins',
    'Lakewood',
    'Boulder',
    'Pueblo',
    'Greeley',
  ],
  'CT': [
    'Bridgeport',
    'New Haven',
    'Stamford',
    'Hartford',
    'Waterbury',
    'Norwalk',
    'Danbury',
    'New Britain',
  ],
  'DE': [
    'Wilmington',
    'Dover',
    'Newark',
    'Middletown',
    'Smyrna',
    'Milford',
    'Seaford',
    'Georgetown',
  ],
  'FL': [
    'Jacksonville',
    'Miami',
    'Tampa',
    'Orlando',
    'St. Petersburg',
    'Hialeah',
    'Tallahassee',
    'Fort Lauderdale',
  ],
  'GA': [
    'Atlanta',
    'Augusta',
    'Columbus',
    'Savannah',
    'Athens',
    'Sandy Springs',
    'Macon',
    'Roswell',
  ],
  'HI': [
    'Honolulu',
    'East Honolulu',
    'Pearl City',
    'Hilo',
    'Kailua',
    'Waipahu',
    'Kaneohe',
    'Mililani',
  ],
  'ID': [
    'Boise',
    'Meridian',
    'Nampa',
    'Idaho Falls',
    'Caldwell',
    'Pocatello',
    'Coeur dAlene',
    'Twin Falls',
  ],
  'IL': [
    'Chicago',
    'Aurora',
    'Naperville',
    'Joliet',
    'Rockford',
    'Springfield',
    'Elgin',
    'Peoria',
  ],
  'IN': [
    'Indianapolis',
    'Fort Wayne',
    'Evansville',
    'South Bend',
    'Carmel',
    'Fishers',
    'Bloomington',
    'Hammond',
  ],
  'IA': [
    'Des Moines',
    'Cedar Rapids',
    'Davenport',
    'Sioux City',
    'Iowa City',
    'Waterloo',
    'Ames',
    'West Des Moines',
  ],
  'KS': [
    'Wichita',
    'Overland Park',
    'Kansas City',
    'Olathe',
    'Topeka',
    'Lawrence',
    'Shawnee',
    'Manhattan',
  ],
  'KY': [
    'Louisville',
    'Lexington',
    'Bowling Green',
    'Owensboro',
    'Covington',
    'Richmond',
    'Georgetown',
    'Florence',
  ],
  'LA': [
    'New Orleans',
    'Baton Rouge',
    'Shreveport',
    'Lafayette',
    'Lake Charles',
    'Kenner',
    'Bossier City',
    'Monroe',
  ],
  'ME': [
    'Portland',
    'Lewiston',
    'Bangor',
    'South Portland',
    'Auburn',
    'Biddeford',
    'Sanford',
    'Augusta',
  ],
  'MD': [
    'Baltimore',
    'Frederick',
    'Rockville',
    'Gaithersburg',
    'Bowie',
    'Hagerstown',
    'Annapolis',
    'College Park',
  ],
  'MA': [
    'Boston',
    'Worcester',
    'Springfield',
    'Cambridge',
    'Lowell',
    'Brockton',
    'Quincy',
    'Lynn',
  ],
  'MI': [
    'Detroit',
    'Grand Rapids',
    'Warren',
    'Sterling Heights',
    'Ann Arbor',
    'Lansing',
    'Flint',
    'Dearborn',
  ],
  'MN': [
    'Minneapolis',
    'St. Paul',
    'Rochester',
    'Duluth',
    'Bloomington',
    'Brooklyn Park',
    'Plymouth',
    'Woodbury',
  ],
  'MS': [
    'Jackson',
    'Gulfport',
    'Southaven',
    'Biloxi',
    'Hattiesburg',
    'Olive Branch',
    'Tupelo',
    'Meridian',
  ],
  'MO': [
    'Kansas City',
    'St. Louis',
    'Springfield',
    'Columbia',
    'Independence',
    'Lees Summit',
    'OFallon',
    'St. Joseph',
  ],
  'MT': [
    'Billings',
    'Missoula',
    'Great Falls',
    'Bozeman',
    'Butte',
    'Helena',
    'Kalispell',
    'Havre',
  ],
  'NE': [
    'Omaha',
    'Lincoln',
    'Bellevue',
    'Grand Island',
    'Kearney',
    'Fremont',
    'Hastings',
    'Norfolk',
  ],
  'NV': [
    'Las Vegas',
    'Henderson',
    'Reno',
    'North Las Vegas',
    'Sparks',
    'Carson City',
    'Elko',
    'Mesquite',
  ],
  'NH': [
    'Manchester',
    'Nashua',
    'Concord',
    'Derry',
    'Dover',
    'Rochester',
    'Salem',
    'Merrimack',
  ],
  'NJ': [
    'Newark',
    'Jersey City',
    'Paterson',
    'Elizabeth',
    'Edison',
    'Trenton',
    'Camden',
    'Clifton',
  ],
  'NM': [
    'Albuquerque',
    'Las Cruces',
    'Rio Rancho',
    'Santa Fe',
    'Roswell',
    'Farmington',
    'Clovis',
    'Hobbs',
  ],
  'NY': [
    'New York',
    'Bronx',
    'Brooklyn',
    'Queens',
    'Staten Island',
    'Yonkers',
    'Buffalo',
    'Rochester',
    'Syracuse',
    'Albany',
  ],
  'NC': [
    'Charlotte',
    'Raleigh',
    'Greensboro',
    'Durham',
    'Winston-Salem',
    'Fayetteville',
    'Cary',
    'Wilmington',
  ],
  'ND': [
    'Fargo',
    'Bismarck',
    'Grand Forks',
    'Minot',
    'West Fargo',
    'Williston',
    'Dickinson',
    'Mandan',
  ],
  'OH': [
    'Columbus',
    'Cleveland',
    'Cincinnati',
    'Toledo',
    'Akron',
    'Dayton',
    'Parma',
    'Canton',
  ],
  'OK': [
    'Oklahoma City',
    'Tulsa',
    'Norman',
    'Broken Arrow',
    'Lawton',
    'Edmond',
    'Moore',
    'Midwest City',
  ],
  'OR': [
    'Portland',
    'Eugene',
    'Salem',
    'Gresham',
    'Hillsboro',
    'Bend',
    'Beaverton',
    'Medford',
  ],
  'PA': [
    'Philadelphia',
    'Pittsburgh',
    'Allentown',
    'Erie',
    'Reading',
    'Scranton',
    'Bethlehem',
    'Harrisburg',
  ],
  'RI': [
    'Providence',
    'Warwick',
    'Cranston',
    'Pawtucket',
    'East Providence',
    'Woonsocket',
    'Newport',
    'Central Falls',
  ],
  'SC': [
    'Charleston',
    'Columbia',
    'North Charleston',
    'Mount Pleasant',
    'Rock Hill',
    'Greenville',
    'Summerville',
    'Sumter',
  ],
  'SD': [
    'Sioux Falls',
    'Rapid City',
    'Aberdeen',
    'Brookings',
    'Watertown',
    'Mitchell',
    'Yankton',
    'Pierre',
  ],
  'TN': [
    'Nashville',
    'Memphis',
    'Knoxville',
    'Chattanooga',
    'Clarksville',
    'Murfreesboro',
    'Franklin',
    'Jackson',
  ],
  'TX': [
    'Houston',
    'San Antonio',
    'Dallas',
    'Austin',
    'Fort Worth',
    'El Paso',
    'Arlington',
    'Corpus Christi',
  ],
  'UT': [
    'Salt Lake City',
    'West Valley City',
    'Provo',
    'West Jordan',
    'Orem',
    'Sandy',
    'Ogden',
    'St. George',
  ],
  'VT': [
    'Burlington',
    'South Burlington',
    'Rutland',
    'Barre',
    'Montpelier',
    'Winooski',
    'St. Albans',
    'Newport',
  ],
  'VA': [
    'Virginia Beach',
    'Norfolk',
    'Chesapeake',
    'Richmond',
    'Arlington',
    'Alexandria',
    'Newport News',
    'Hampton',
  ],
  'WA': [
    'Seattle',
    'Spokane',
    'Tacoma',
    'Vancouver',
    'Bellevue',
    'Kent',
    'Everett',
    'Olympia',
  ],
  'WV': [
    'Charleston',
    'Huntington',
    'Morgantown',
    'Parkersburg',
    'Wheeling',
    'Weirton',
    'Fairmont',
    'Martinsburg',
  ],
  'WI': [
    'Milwaukee',
    'Madison',
    'Green Bay',
    'Kenosha',
    'Racine',
    'Appleton',
    'Waukesha',
    'Eau Claire',
  ],
  'WY': [
    'Cheyenne',
    'Casper',
    'Laramie',
    'Gillette',
    'Rock Springs',
    'Sheridan',
    'Green River',
    'Evanston',
  ],
  'DC': ['Washington'],
};

export const OTHER_CITY = "Other";

export type UsStateOption = { code: string; name: string };

export const US_STATE_OPTIONS: UsStateOption[] = Object.entries(US_STATE_NAMES)
  .map(([code, name]) => ({ code, name }))
  .sort((a, b) => a.name.localeCompare(b.name));

export function citiesForState(stateCode: string): string[] {
  const list = CITIES_BY_STATE[(stateCode || "").toUpperCase()] ?? [];
  return [...list, OTHER_CITY];
}

// Keep a currently-selected value visible even if it is not in the canonical list.
export function withSelected(values: string[], current: string): string[] {
  if (current && !values.includes(current)) return [current, ...values];
  return values;
}
