/* eslint-disable max-len */

const ALL_COUNTRIES = [
  {"id": "afghanistan", "name": "Afghanistan", "code": "AF", "sortOrder": 0},
  {"id": "albania", "name": "Albania", "code": "AL", "sortOrder": 1},
  {"id": "algeria", "name": "Algeria", "code": "DZ", "sortOrder": 2},
  {"id": "american-samoa", "name": "American Samoa", "code": "AS", "sortOrder": 3},
  {"id": "andorra", "name": "Andorra", "code": "AD", "sortOrder": 4},
  {"id": "angola", "name": "Angola", "code": "AO", "sortOrder": 5},
  {"id": "anguilla", "name": "Anguilla", "code": "AI", "sortOrder": 6},
  {"id": "antarctica", "name": "Antarctica", "code": "AQ", "sortOrder": 7},
  {"id": "antigua-and-barbuda", "name": "Antigua and Barbuda", "code": "AG", "sortOrder": 8},
  {"id": "argentina", "name": "Argentina", "code": "AR", "sortOrder": 9},
  {"id": "armenia", "name": "Armenia", "code": "AM", "sortOrder": 10},
  {"id": "aruba", "name": "Aruba", "code": "AW", "sortOrder": 11},
  {"id": "australia", "name": "Australia", "code": "AU", "sortOrder": 12},
  {"id": "austria", "name": "Austria", "code": "AT", "sortOrder": 13},
  {"id": "azerbaijan", "name": "Azerbaijan", "code": "AZ", "sortOrder": 14},
  {"id": "bahamas", "name": "Bahamas", "code": "BS", "sortOrder": 15},
  {"id": "bahrain", "name": "Bahrain", "code": "BH", "sortOrder": 16},
  {"id": "bangladesh", "name": "Bangladesh", "code": "BD", "sortOrder": 17},
  {"id": "barbados", "name": "Barbados", "code": "BB", "sortOrder": 18},
  {"id": "belarus", "name": "Belarus", "code": "BY", "sortOrder": 19},
  {"id": "belgium", "name": "Belgium", "code": "BE", "sortOrder": 20},
  {"id": "belize", "name": "Belize", "code": "BZ", "sortOrder": 21},
  {"id": "benin", "name": "Benin", "code": "BJ", "sortOrder": 22},
  {"id": "bermuda", "name": "Bermuda", "code": "BM", "sortOrder": 23},
  {"id": "bhutan", "name": "Bhutan", "code": "BT", "sortOrder": 24},
  {"id": "bolivia", "name": "Bolivia", "code": "BO", "sortOrder": 25},
  {"id": "bonaire-sint-eustatius-and-saba", "name": "Bonaire, Sint Eustatius and Saba", "code": "BQ", "sortOrder": 26},
  {"id": "bosnia-and-herzegovina", "name": "Bosnia and Herzegovina", "code": "BA", "sortOrder": 27},
  {"id": "botswana", "name": "Botswana", "code": "BW", "sortOrder": 28},
  {"id": "bouvet-island", "name": "Bouvet Island", "code": "BV", "sortOrder": 29},
  {"id": "brazil", "name": "Brazil", "code": "BR", "sortOrder": 30},
  {"id": "british-indian-ocean-territory", "name": "British Indian Ocean Territory", "code": "IO", "sortOrder": 31},
  {"id": "brunei-darussalam", "name": "Brunei Darussalam", "code": "BN", "sortOrder": 32},
  {"id": "bulgaria", "name": "Bulgaria", "code": "BG", "sortOrder": 33},
  {"id": "burkina-faso", "name": "Burkina Faso", "code": "BF", "sortOrder": 34},
  {"id": "burundi", "name": "Burundi", "code": "BI", "sortOrder": 35},
  {"id": "cabo-verde", "name": "Cabo Verde", "code": "CV", "sortOrder": 36},
  {"id": "cambodia", "name": "Cambodia", "code": "KH", "sortOrder": 37},
  {"id": "cameroon", "name": "Cameroon", "code": "CM", "sortOrder": 38},
  {"id": "canada", "name": "Canada", "code": "CA", "sortOrder": 39},
  {"id": "cayman-islands", "name": "Cayman Islands", "code": "KY", "sortOrder": 40},
  {"id": "central-african-republic", "name": "Central African Republic", "code": "CF", "sortOrder": 41},
  {"id": "chad", "name": "Chad", "code": "TD", "sortOrder": 42},
  {"id": "chile", "name": "Chile", "code": "CL", "sortOrder": 43},
  {"id": "china", "name": "China", "code": "CN", "sortOrder": 44},
  {"id": "christmas-island", "name": "Christmas Island", "code": "CX", "sortOrder": 45},
  {"id": "cocos-keeling-islands", "name": "Cocos (Keeling) Islands", "code": "CC", "sortOrder": 46},
  {"id": "colombia", "name": "Colombia", "code": "CO", "sortOrder": 47},
  {"id": "comoros", "name": "Comoros", "code": "KM", "sortOrder": 48},
  {"id": "congo", "name": "Congo", "code": "CG", "sortOrder": 49},
  {"id": "congo-the-democratic-republic-of-the", "name": "Congo, The Democratic Republic of the", "code": "CD", "sortOrder": 50},
  {"id": "cook-islands", "name": "Cook Islands", "code": "CK", "sortOrder": 51},
  {"id": "costa-rica", "name": "Costa Rica", "code": "CR", "sortOrder": 52},
  {"id": "croatia", "name": "Croatia", "code": "HR", "sortOrder": 53},
  {"id": "cuba", "name": "Cuba", "code": "CU", "sortOrder": 54},
  {"id": "cura-ao", "name": "Curaçao", "code": "CW", "sortOrder": 55},
  {"id": "cyprus", "name": "Cyprus", "code": "CY", "sortOrder": 56},
  {"id": "czechia", "name": "Czechia", "code": "CZ", "sortOrder": 57},
  {"id": "c-te-d-ivoire", "name": "Côte d'Ivoire", "code": "CI", "sortOrder": 58},
  {"id": "denmark", "name": "Denmark", "code": "DK", "sortOrder": 59},
  {"id": "djibouti", "name": "Djibouti", "code": "DJ", "sortOrder": 60},
  {"id": "dominica", "name": "Dominica", "code": "DM", "sortOrder": 61},
  {"id": "dominican-republic", "name": "Dominican Republic", "code": "DO", "sortOrder": 62},
  {"id": "ecuador", "name": "Ecuador", "code": "EC", "sortOrder": 63},
  {"id": "egypt", "name": "Egypt", "code": "EG", "sortOrder": 64},
  {"id": "el-salvador", "name": "El Salvador", "code": "SV", "sortOrder": 65},
  {"id": "equatorial-guinea", "name": "Equatorial Guinea", "code": "GQ", "sortOrder": 66},
  {"id": "eritrea", "name": "Eritrea", "code": "ER", "sortOrder": 67},
  {"id": "estonia", "name": "Estonia", "code": "EE", "sortOrder": 68},
  {"id": "eswatini", "name": "Eswatini", "code": "SZ", "sortOrder": 69},
  {"id": "ethiopia", "name": "Ethiopia", "code": "ET", "sortOrder": 70},
  {"id": "falkland-islands-malvinas", "name": "Falkland Islands (Malvinas)", "code": "FK", "sortOrder": 71},
  {"id": "faroe-islands", "name": "Faroe Islands", "code": "FO", "sortOrder": 72},
  {"id": "fiji", "name": "Fiji", "code": "FJ", "sortOrder": 73},
  {"id": "finland", "name": "Finland", "code": "FI", "sortOrder": 74},
  {"id": "france", "name": "France", "code": "FR", "sortOrder": 75},
  {"id": "french-guiana", "name": "French Guiana", "code": "GF", "sortOrder": 76},
  {"id": "french-polynesia", "name": "French Polynesia", "code": "PF", "sortOrder": 77},
  {"id": "french-southern-territories", "name": "French Southern Territories", "code": "TF", "sortOrder": 78},
  {"id": "gabon", "name": "Gabon", "code": "GA", "sortOrder": 79},
  {"id": "gambia", "name": "Gambia", "code": "GM", "sortOrder": 80},
  {"id": "georgia", "name": "Georgia", "code": "GE", "sortOrder": 81},
  {"id": "germany", "name": "Germany", "code": "DE", "sortOrder": 82},
  {"id": "ghana", "name": "Ghana", "code": "GH", "sortOrder": 83},
  {"id": "gibraltar", "name": "Gibraltar", "code": "GI", "sortOrder": 84},
  {"id": "greece", "name": "Greece", "code": "GR", "sortOrder": 85},
  {"id": "greenland", "name": "Greenland", "code": "GL", "sortOrder": 86},
  {"id": "grenada", "name": "Grenada", "code": "GD", "sortOrder": 87},
  {"id": "guadeloupe", "name": "Guadeloupe", "code": "GP", "sortOrder": 88},
  {"id": "guam", "name": "Guam", "code": "GU", "sortOrder": 89},
  {"id": "guatemala", "name": "Guatemala", "code": "GT", "sortOrder": 90},
  {"id": "guernsey", "name": "Guernsey", "code": "GG", "sortOrder": 91},
  {"id": "guinea", "name": "Guinea", "code": "GN", "sortOrder": 92},
  {"id": "guinea-bissau", "name": "Guinea-Bissau", "code": "GW", "sortOrder": 93},
  {"id": "guyana", "name": "Guyana", "code": "GY", "sortOrder": 94},
  {"id": "haiti", "name": "Haiti", "code": "HT", "sortOrder": 95},
  {"id": "heard-island-and-mcdonald-islands", "name": "Heard Island and McDonald Islands", "code": "HM", "sortOrder": 96},
  {"id": "holy-see-vatican-city-state", "name": "Holy See (Vatican City State)", "code": "VA", "sortOrder": 97},
  {"id": "honduras", "name": "Honduras", "code": "HN", "sortOrder": 98},
  {"id": "hong-kong", "name": "Hong Kong", "code": "HK", "sortOrder": 99},
  {"id": "hungary", "name": "Hungary", "code": "HU", "sortOrder": 100},
  {"id": "iceland", "name": "Iceland", "code": "IS", "sortOrder": 101},
  {"id": "india", "name": "India", "code": "IN", "sortOrder": 102},
  {"id": "indonesia", "name": "Indonesia", "code": "ID", "sortOrder": 103},
  {"id": "iran", "name": "Iran", "code": "IR", "sortOrder": 104},
  {"id": "iraq", "name": "Iraq", "code": "IQ", "sortOrder": 105},
  {"id": "ireland", "name": "Ireland", "code": "IE", "sortOrder": 106},
  {"id": "isle-of-man", "name": "Isle of Man", "code": "IM", "sortOrder": 107},
  {"id": "israel", "name": "Israel", "code": "IL", "sortOrder": 108},
  {"id": "italy", "name": "Italy", "code": "IT", "sortOrder": 109},
  {"id": "jamaica", "name": "Jamaica", "code": "JM", "sortOrder": 110},
  {"id": "japan", "name": "Japan", "code": "JP", "sortOrder": 111},
  {"id": "jersey", "name": "Jersey", "code": "JE", "sortOrder": 112},
  {"id": "jordan", "name": "Jordan", "code": "JO", "sortOrder": 113},
  {"id": "kazakhstan", "name": "Kazakhstan", "code": "KZ", "sortOrder": 114},
  {"id": "kenya", "name": "Kenya", "code": "KE", "sortOrder": 115},
  {"id": "kiribati", "name": "Kiribati", "code": "KI", "sortOrder": 116},
  {"id": "north-korea", "name": "North Korea", "code": "KP", "sortOrder": 117},
  {"id": "south-korea", "name": "South Korea", "code": "KR", "sortOrder": 118},
  {"id": "kuwait", "name": "Kuwait", "code": "KW", "sortOrder": 119},
  {"id": "kyrgyzstan", "name": "Kyrgyzstan", "code": "KG", "sortOrder": 120},
  {"id": "laos", "name": "Laos", "code": "LA", "sortOrder": 121},
  {"id": "latvia", "name": "Latvia", "code": "LV", "sortOrder": 122},
  {"id": "lebanon", "name": "Lebanon", "code": "LB", "sortOrder": 123},
  {"id": "lesotho", "name": "Lesotho", "code": "LS", "sortOrder": 124},
  {"id": "liberia", "name": "Liberia", "code": "LR", "sortOrder": 125},
  {"id": "libya", "name": "Libya", "code": "LY", "sortOrder": 126},
  {"id": "liechtenstein", "name": "Liechtenstein", "code": "LI", "sortOrder": 127},
  {"id": "lithuania", "name": "Lithuania", "code": "LT", "sortOrder": 128},
  {"id": "luxembourg", "name": "Luxembourg", "code": "LU", "sortOrder": 129},
  {"id": "macao", "name": "Macao", "code": "MO", "sortOrder": 130},
  {"id": "madagascar", "name": "Madagascar", "code": "MG", "sortOrder": 131},
  {"id": "malawi", "name": "Malawi", "code": "MW", "sortOrder": 132},
  {"id": "malaysia", "name": "Malaysia", "code": "MY", "sortOrder": 133},
  {"id": "maldives", "name": "Maldives", "code": "MV", "sortOrder": 134},
  {"id": "mali", "name": "Mali", "code": "ML", "sortOrder": 135},
  {"id": "malta", "name": "Malta", "code": "MT", "sortOrder": 136},
  {"id": "marshall-islands", "name": "Marshall Islands", "code": "MH", "sortOrder": 137},
  {"id": "martinique", "name": "Martinique", "code": "MQ", "sortOrder": 138},
  {"id": "mauritania", "name": "Mauritania", "code": "MR", "sortOrder": 139},
  {"id": "mauritius", "name": "Mauritius", "code": "MU", "sortOrder": 140},
  {"id": "mayotte", "name": "Mayotte", "code": "YT", "sortOrder": 141},
  {"id": "mexico", "name": "Mexico", "code": "MX", "sortOrder": 142},
  {"id": "micronesia-federated-states-of", "name": "Micronesia, Federated States of", "code": "FM", "sortOrder": 143},
  {"id": "moldova", "name": "Moldova", "code": "MD", "sortOrder": 144},
  {"id": "monaco", "name": "Monaco", "code": "MC", "sortOrder": 145},
  {"id": "mongolia", "name": "Mongolia", "code": "MN", "sortOrder": 146},
  {"id": "montenegro", "name": "Montenegro", "code": "ME", "sortOrder": 147},
  {"id": "montserrat", "name": "Montserrat", "code": "MS", "sortOrder": 148},
  {"id": "morocco", "name": "Morocco", "code": "MA", "sortOrder": 149},
  {"id": "mozambique", "name": "Mozambique", "code": "MZ", "sortOrder": 150},
  {"id": "myanmar", "name": "Myanmar", "code": "MM", "sortOrder": 151},
  {"id": "namibia", "name": "Namibia", "code": "NA", "sortOrder": 152},
  {"id": "nauru", "name": "Nauru", "code": "NR", "sortOrder": 153},
  {"id": "nepal", "name": "Nepal", "code": "NP", "sortOrder": 154},
  {"id": "netherlands", "name": "Netherlands", "code": "NL", "sortOrder": 155},
  {"id": "new-caledonia", "name": "New Caledonia", "code": "NC", "sortOrder": 156},
  {"id": "new-zealand", "name": "New Zealand", "code": "NZ", "sortOrder": 157},
  {"id": "nicaragua", "name": "Nicaragua", "code": "NI", "sortOrder": 158},
  {"id": "niger", "name": "Niger", "code": "NE", "sortOrder": 159},
  {"id": "nigeria", "name": "Nigeria", "code": "NG", "sortOrder": 160},
  {"id": "niue", "name": "Niue", "code": "NU", "sortOrder": 161},
  {"id": "norfolk-island", "name": "Norfolk Island", "code": "NF", "sortOrder": 162},
  {"id": "north-macedonia", "name": "North Macedonia", "code": "MK", "sortOrder": 163},
  {"id": "northern-mariana-islands", "name": "Northern Mariana Islands", "code": "MP", "sortOrder": 164},
  {"id": "norway", "name": "Norway", "code": "NO", "sortOrder": 165},
  {"id": "oman", "name": "Oman", "code": "OM", "sortOrder": 166},
  {"id": "pakistan", "name": "Pakistan", "code": "PK", "sortOrder": 167},
  {"id": "palau", "name": "Palau", "code": "PW", "sortOrder": 168},
  {"id": "palestine-state-of", "name": "Palestine, State of", "code": "PS", "sortOrder": 169},
  {"id": "panama", "name": "Panama", "code": "PA", "sortOrder": 170},
  {"id": "papua-new-guinea", "name": "Papua New Guinea", "code": "PG", "sortOrder": 171},
  {"id": "paraguay", "name": "Paraguay", "code": "PY", "sortOrder": 172},
  {"id": "peru", "name": "Peru", "code": "PE", "sortOrder": 173},
  {"id": "philippines", "name": "Philippines", "code": "PH", "sortOrder": 174},
  {"id": "pitcairn", "name": "Pitcairn", "code": "PN", "sortOrder": 175},
  {"id": "poland", "name": "Poland", "code": "PL", "sortOrder": 176},
  {"id": "portugal", "name": "Portugal", "code": "PT", "sortOrder": 177},
  {"id": "puerto-rico", "name": "Puerto Rico", "code": "PR", "sortOrder": 178},
  {"id": "qatar", "name": "Qatar", "code": "QA", "sortOrder": 179},
  {"id": "romania", "name": "Romania", "code": "RO", "sortOrder": 180},
  {"id": "russian-federation", "name": "Russian Federation", "code": "RU", "sortOrder": 181},
  {"id": "rwanda", "name": "Rwanda", "code": "RW", "sortOrder": 182},
  {"id": "r-union", "name": "Réunion", "code": "RE", "sortOrder": 183},
  {"id": "saint-barth-lemy", "name": "Saint Barthélemy", "code": "BL", "sortOrder": 184},
  {"id": "saint-helena-ascension-and-tristan-da-cunha", "name": "Saint Helena, Ascension and Tristan da Cunha", "code": "SH", "sortOrder": 185},
  {"id": "saint-kitts-and-nevis", "name": "Saint Kitts and Nevis", "code": "KN", "sortOrder": 186},
  {"id": "saint-lucia", "name": "Saint Lucia", "code": "LC", "sortOrder": 187},
  {"id": "saint-martin-french-part", "name": "Saint Martin (French part)", "code": "MF", "sortOrder": 188},
  {"id": "saint-pierre-and-miquelon", "name": "Saint Pierre and Miquelon", "code": "PM", "sortOrder": 189},
  {"id": "saint-vincent-and-the-grenadines", "name": "Saint Vincent and the Grenadines", "code": "VC", "sortOrder": 190},
  {"id": "samoa", "name": "Samoa", "code": "WS", "sortOrder": 191},
  {"id": "san-marino", "name": "San Marino", "code": "SM", "sortOrder": 192},
  {"id": "sao-tome-and-principe", "name": "Sao Tome and Principe", "code": "ST", "sortOrder": 193},
  {"id": "saudi-arabia", "name": "Saudi Arabia", "code": "SA", "sortOrder": 194},
  {"id": "senegal", "name": "Senegal", "code": "SN", "sortOrder": 195},
  {"id": "serbia", "name": "Serbia", "code": "RS", "sortOrder": 196},
  {"id": "seychelles", "name": "Seychelles", "code": "SC", "sortOrder": 197},
  {"id": "sierra-leone", "name": "Sierra Leone", "code": "SL", "sortOrder": 198},
  {"id": "singapore", "name": "Singapore", "code": "SG", "sortOrder": 199},
  {"id": "sint-maarten-dutch-part", "name": "Sint Maarten (Dutch part)", "code": "SX", "sortOrder": 200},
  {"id": "slovakia", "name": "Slovakia", "code": "SK", "sortOrder": 201},
  {"id": "slovenia", "name": "Slovenia", "code": "SI", "sortOrder": 202},
  {"id": "solomon-islands", "name": "Solomon Islands", "code": "SB", "sortOrder": 203},
  {"id": "somalia", "name": "Somalia", "code": "SO", "sortOrder": 204},
  {"id": "south-africa", "name": "South Africa", "code": "ZA", "sortOrder": 205},
  {"id": "south-georgia-and-the-south-sandwich-islands", "name": "South Georgia and the South Sandwich Islands", "code": "GS", "sortOrder": 206},
  {"id": "south-sudan", "name": "South Sudan", "code": "SS", "sortOrder": 207},
  {"id": "spain", "name": "Spain", "code": "ES", "sortOrder": 208},
  {"id": "sri-lanka", "name": "Sri Lanka", "code": "LK", "sortOrder": 209},
  {"id": "sudan", "name": "Sudan", "code": "SD", "sortOrder": 210},
  {"id": "suriname", "name": "Suriname", "code": "SR", "sortOrder": 211},
  {"id": "svalbard-and-jan-mayen", "name": "Svalbard and Jan Mayen", "code": "SJ", "sortOrder": 212},
  {"id": "sweden", "name": "Sweden", "code": "SE", "sortOrder": 213},
  {"id": "switzerland", "name": "Switzerland", "code": "CH", "sortOrder": 214},
  {"id": "syria", "name": "Syria", "code": "SY", "sortOrder": 215},
  {"id": "taiwan", "name": "Taiwan", "code": "TW", "sortOrder": 216},
  {"id": "tajikistan", "name": "Tajikistan", "code": "TJ", "sortOrder": 217},
  {"id": "tanzania", "name": "Tanzania", "code": "TZ", "sortOrder": 218},
  {"id": "thailand", "name": "Thailand", "code": "TH", "sortOrder": 219},
  {"id": "timor-leste", "name": "Timor-Leste", "code": "TL", "sortOrder": 220},
  {"id": "togo", "name": "Togo", "code": "TG", "sortOrder": 221},
  {"id": "tokelau", "name": "Tokelau", "code": "TK", "sortOrder": 222},
  {"id": "tonga", "name": "Tonga", "code": "TO", "sortOrder": 223},
  {"id": "trinidad-and-tobago", "name": "Trinidad and Tobago", "code": "TT", "sortOrder": 224},
  {"id": "tunisia", "name": "Tunisia", "code": "TN", "sortOrder": 225},
  {"id": "turkmenistan", "name": "Turkmenistan", "code": "TM", "sortOrder": 226},
  {"id": "turks-and-caicos-islands", "name": "Turks and Caicos Islands", "code": "TC", "sortOrder": 227},
  {"id": "tuvalu", "name": "Tuvalu", "code": "TV", "sortOrder": 228},
  {"id": "t-rkiye", "name": "Türkiye", "code": "TR", "sortOrder": 229},
  {"id": "uganda", "name": "Uganda", "code": "UG", "sortOrder": 230},
  {"id": "ukraine", "name": "Ukraine", "code": "UA", "sortOrder": 231},
  {"id": "united-arab-emirates", "name": "United Arab Emirates", "code": "AE", "sortOrder": 232},
  {"id": "united-kingdom", "name": "United Kingdom", "code": "GB", "sortOrder": 233},
  {"id": "united-states", "name": "United States", "code": "US", "sortOrder": 234},
  {"id": "united-states-minor-outlying-islands", "name": "United States Minor Outlying Islands", "code": "UM", "sortOrder": 235},
  {"id": "uruguay", "name": "Uruguay", "code": "UY", "sortOrder": 236},
  {"id": "uzbekistan", "name": "Uzbekistan", "code": "UZ", "sortOrder": 237},
  {"id": "vanuatu", "name": "Vanuatu", "code": "VU", "sortOrder": 238},
  {"id": "venezuela", "name": "Venezuela", "code": "VE", "sortOrder": 239},
  {"id": "vietnam", "name": "Vietnam", "code": "VN", "sortOrder": 240},
  {"id": "virgin-islands-british", "name": "Virgin Islands, British", "code": "VG", "sortOrder": 241},
  {"id": "virgin-islands-u-s", "name": "Virgin Islands, U.S.", "code": "VI", "sortOrder": 242},
  {"id": "wallis-and-futuna", "name": "Wallis and Futuna", "code": "WF", "sortOrder": 243},
  {"id": "western-sahara", "name": "Western Sahara", "code": "EH", "sortOrder": 244},
  {"id": "yemen", "name": "Yemen", "code": "YE", "sortOrder": 245},
  {"id": "zambia", "name": "Zambia", "code": "ZM", "sortOrder": 246},
  {"id": "zimbabwe", "name": "Zimbabwe", "code": "ZW", "sortOrder": 247},
  {"id": "land-islands", "name": "Åland Islands", "code": "AX", "sortOrder": 248},
];

module.exports = {ALL_COUNTRIES};
